#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build complete German blog translations for Tuttilo."""
import json
import sys

de = {}

# ═══════════════════════════════════════════════
# 1. how-to-compress-pdf
# ═══════════════════════════════════════════════
de["how-to-compress-pdf"] = {
    "s1": {
        "h": "Warum PDF-Dateien so gro\u00df werden",
        "p": "PDF-Dateien k\u00f6nnen aus verschiedenen Gr\u00fcnden \u00fcberraschend gro\u00df werden. Hochaufl\u00f6sende Bilder, die in Dokumenten eingebettet sind, sind die Hauptursache \u2013 besonders wenn gescannte Dokumente unkomprimierte Bilddaten enthalten. Jede Seite eines gescannten Dokuments kann ein Foto in voller Aufl\u00f6sung enthalten, was sich schnell auf Dutzende Megabyte summiert.\n\nAuch eingebettete Schriftarten tragen zur Dateigr\u00f6\u00dfe bei. Wenn ein PDF benutzerdefinierte Schriftarten enth\u00e4lt, um eine konsistente Darstellung auf allen Ger\u00e4ten zu gew\u00e4hrleisten, f\u00fcgt jede Schriftdatei Gewicht hinzu. Dar\u00fcber hinaus erh\u00f6hen Metadaten, Formularfelder, Anmerkungen und eingebettete Multimedia-Inhalte die Gesamtdateigr\u00f6\u00dfe. Das Verst\u00e4ndnis dieser Faktoren hilft Ihnen, die richtige Komprimierungsstrategie zu w\u00e4hlen."
    },
    "s2": {
        "h": "Verschiedene PDF-Komprimierungsmethoden erkl\u00e4rt",
        "p": "Die PDF-Komprimierung l\u00e4sst sich in zwei Hauptkategorien einteilen: verlustbehaftet und verlustfrei. Die verlustfreie Komprimierung reduziert die Dateigr\u00f6\u00dfe ohne jegliche Qualit\u00e4tseinbu\u00dfen, indem redundante Daten entfernt und die Dateistruktur optimiert werden. Diese Methode eignet sich gut f\u00fcr textlastige Dokumente, bei denen jedes Detail z\u00e4hlt.\n\nDie verlustbehaftete Komprimierung erzielt eine gr\u00f6\u00dfere Reduzierung durch strategische Verringerung der Bildqualit\u00e4t und Aufl\u00f6sung. Moderne Algorithmen komprimieren Bilder intelligent und bewahren dabei die visuelle Wiedergabetreue. Der Schl\u00fcssel liegt darin, die richtige Balance zu finden \u2013 ausreichende Komprimierung zur Reduzierung der Dateigr\u00f6\u00dfe ohne sp\u00fcrbaren Qualit\u00e4tsverlust. Tuttilos PDF-Kompressor verwendet fortschrittliche Algorithmen, die dieses Gleichgewicht f\u00fcr die meisten Anwendungsf\u00e4lle automatisch optimieren."
    },
    "s3": {
        "h": "Schritt f\u00fcr Schritt: PDFs mit Tuttilo komprimieren",
        "p": "Das Komprimieren Ihrer PDF-Dateien mit Tuttilo ist unkompliziert und erfordert keine Softwareinstallation. Navigieren Sie zun\u00e4chst zu tuttilo.com und w\u00e4hlen Sie das PDF-Komprimierungstool aus der Kategorie Dokumente. Klicken Sie auf den Upload-Bereich oder ziehen Sie Ihre PDF-Datei direkt in das Browserfenster.\n\nNach dem Hochladen w\u00e4hlen Sie Ihre Komprimierungsstufe: niedrig (minimale Komprimierung, h\u00f6chste Qualit\u00e4t), mittel (ausgewogener Ansatz) oder hoch (maximale Komprimierung). F\u00fcr die meisten Dokumente liefert die mittlere Komprimierung hervorragende Ergebnisse. Klicken Sie auf \u201eKomprimieren\u201c und warten Sie, w\u00e4hrend das Tool Ihre Datei verarbeitet. Die Komprimierung erfolgt vollst\u00e4ndig in Ihrem Browser \u2013 Ihre Datei verl\u00e4sst nie Ihr Ger\u00e4t, was vollst\u00e4ndige Privatsph\u00e4re gew\u00e4hrleistet. Laden Sie das komprimierte PDF herunter und vergleichen Sie die Dateigr\u00f6\u00dfenreduzierung."
    },
    "s4": {
        "h": "Tipps f\u00fcr beste Komprimierungsergebnisse",
        "p": "Um optimale Komprimierungsergebnisse zu erzielen, sollten Sie den Verwendungszweck Ihres Dokuments ber\u00fccksichtigen, bevor Sie eine Komprimierungsstufe w\u00e4hlen. Dokumente, die zum Drucken bestimmt sind, erfordern h\u00f6here Qualit\u00e4tseinstellungen, w\u00e4hrend Dateien f\u00fcr E-Mail oder Web-Anzeige eine aggressivere Komprimierung vertragen.\n\nBei Dokumenten mit vielen Bildern liefert die Voroptimierung der Bilder vor der PDF-Erstellung bessere Ergebnisse. Verwenden Sie eine angemessene Aufl\u00f6sung \u2013 300 DPI f\u00fcr Druck, 72-150 DPI f\u00fcr Bildschirmdarstellung. Entfernen Sie unn\u00f6tige Seiten, Anmerkungen oder eingebettete Dateien vor der Komprimierung. Falls Ihr PDF Formulare oder ausf\u00fcllbare Felder enth\u00e4lt, testen Sie die komprimierte Version, um sicherzustellen, dass die Funktionalit\u00e4t erhalten bleibt. Die Stapelverarbeitung mehrerer \u00e4hnlicher Dokumente mit denselben Einstellungen spart Zeit und gew\u00e4hrleistet Konsistenz."
    },
    "s5": {
        "h": "Wann verschiedene Komprimierungsstufen sinnvoll sind",
        "p": "Niedrige Komprimierung ist ideal f\u00fcr Rechtsdokumente, Vertr\u00e4ge, Architekturpl\u00e4ne oder jedes Material, bei dem absolute Pr\u00e4zision wichtig ist. Die Dateigr\u00f6\u00dfenreduzierung wird moderat sein, typischerweise 10-30%, aber die Qualit\u00e4t bleibt makellos.\n\nMittlere Komprimierung eignet sich f\u00fcr die meisten allt\u00e4glichen Anwendungsf\u00e4lle: Gesch\u00e4ftsberichte, Pr\u00e4sentationen, Marketingmaterialien und Rechnungen. Sie erzielen 40-60% Gr\u00f6\u00dfenreduzierung bei f\u00fcr die meisten Betrachter unmerklichem Qualit\u00e4tsverlust. Hohe Komprimierung eignet sich am besten f\u00fcr interne Dokumente, Entw\u00fcrfe, E-Mail-Anh\u00e4nge mit Gr\u00f6\u00dfenbeschr\u00e4nkungen oder Archivierungszwecke, bei denen Lesbarkeit wichtiger ist als perfekte Wiedergabe. Diese Einstellung kann die Dateigr\u00f6\u00dfe um 70% oder mehr reduzieren."
    },
    "s6": {
        "h": "H\u00e4ufige Fehler, die es zu vermeiden gilt",
        "p": "Viele Nutzer machen den Fehler, bereits komprimierte Dateien wiederholt zu komprimieren, was die Qualit\u00e4t verschlechtert, ohne wesentliche Gr\u00f6\u00dfenvorteile zu bringen. Jeder Komprimierungszyklus f\u00fchrt Artefakte ein, insbesondere bei verlustbehafteten Methoden.\n\nVermeiden Sie die Verwendung maximaler Komprimierung bei Dokumenten mit kleinem Text, feinen Linien oder detaillierten Diagrammen \u2013 diese Elemente werden unscharf und schwer lesbar. Komprimieren Sie keine Dateien, bevor Sie deren endg\u00fcltigen Verwendungszweck kennen; wenn Sie sp\u00e4ter Druckqualit\u00e4t aus einer stark komprimierten Datei ben\u00f6tigen, m\u00fcssen Sie vom Original neu beginnen. Bewahren Sie Ihr unkomprimiertes Original-PDF immer als Masterkopie auf. \u00dcberpr\u00fcfen Sie schlie\u00dflich die komprimierte Datei, bevor Sie das Original l\u00f6schen, um sicherzustellen, dass das Ergebnis Ihren Anforderungen entspricht."
    }
}

# ═══════════════════════════════════════════════
# 2. how-to-convert-images
# ═══════════════════════════════════════════════
de["how-to-convert-images"] = {
    "s1": {
        "h": "Bildformate verstehen",
        "p": "Verschiedene Bildformate dienen unterschiedlichen Zwecken, und das Verst\u00e4ndnis ihrer St\u00e4rken hilft Ihnen bei der richtigen Wahl. JPEG ist ideal f\u00fcr Fotografien und komplexe Bilder mit vielen Farben und nutzt verlustbehaftete Komprimierung f\u00fcr kleine Dateigr\u00f6\u00dfen. PNG eignet sich hervorragend f\u00fcr Grafiken mit Transparenz, Text oder scharfen Kanten und nutzt verlustfreie Komprimierung, die jedes Pixel bewahrt.\n\nWebP, ein modernes von Google entwickeltes Format, bietet im Vergleich zu JPEG und PNG \u00fcberlegene Komprimierung und unterst\u00fctzt dabei sowohl verlustbehaftete als auch verlustfreie Modi sowie Transparenz. AVIF, das neueste Format, bietet noch bessere Komprimierung, hat aber eingeschr\u00e4nkte Browser-Unterst\u00fctzung. GIF bleibt trotz seiner 256-Farben-Beschr\u00e4nkung n\u00fctzlich f\u00fcr einfache Animationen. SVG ist perfekt f\u00fcr Logos und Icons, da es vektorbasiert ist und ohne Qualit\u00e4tsverlust beliebig skaliert werden kann."
    },
    "s2": {
        "h": "Wann eine Bildformat-Konvertierung n\u00f6tig ist",
        "p": "Verschiedene Szenarien erfordern eine Bildformat-Konvertierung. Webentwickler konvertieren Bilder zu WebP oder AVIF, um Seitenladegeschwindigkeit und Performance-Werte zu verbessern. E-Commerce-Verk\u00e4ufer konvertieren Produktfotos in die von verschiedenen Plattformen geforderten Formate \u2013 Amazon, eBay und Shopify haben jeweils spezifische Anforderungen.\n\nDesigner konvertieren zwischen Formaten, wenn sie Dateien f\u00fcr Druck im Vergleich zur Web-Nutzung vorbereiten. Druck erfordert typischerweise hochaufl\u00f6sendes TIFF oder unkomprimiertes PNG, w\u00e4hrend Web komprimiertes JPEG oder WebP ben\u00f6tigt. Social-Media-Plattformen verlangen oft bestimmte Formate und Abmessungen. Die Konvertierung von PNG-Screenshots zu JPEG reduziert die Dateigr\u00f6\u00dfe f\u00fcr E-Mail-Anh\u00e4nge. Entwickler konvertieren Bilder, um sie an die Anforderungen ihres Frameworks oder CMS anzupassen. Legacy-Systeme erfordern m\u00f6glicherweise \u00e4ltere Formate, w\u00e4hrend moderne Anwendungen neuere, effizientere Formate bevorzugen."
    },
    "s3": {
        "h": "Schritt-f\u00fcr-Schritt-Bildkonvertierung mit Tuttilo",
        "p": "Das Konvertieren von Bildern mit Tuttilo ist bemerkenswert einfach und erfolgt f\u00fcr maximale Privatsph\u00e4re vollst\u00e4ndig in Ihrem Browser. Besuchen Sie tuttilo.com und navigieren Sie zum Bildkonverter-Tool in der Kategorie Bilder. Laden Sie Ihr Bild hoch, indem Sie auf den Upload-Bereich klicken oder Dateien direkt ins Fenster ziehen.\n\nW\u00e4hlen Sie Ihr gew\u00fcnschtes Ausgabeformat aus dem Dropdown-Men\u00fc \u2013 JPEG, PNG, WebP, AVIF, GIF oder BMP. F\u00fcr JPEG und WebP k\u00f6nnen Sie den Qualit\u00e4tsregler anpassen, um Dateigr\u00f6\u00dfe und Bildqualit\u00e4t abzuw\u00e4gen. Qualit\u00e4tseinstellungen zwischen 75-90 liefern f\u00fcr die meisten Bilder hervorragende Ergebnisse. Klicken Sie auf \u201eKonvertieren\u201c und das Tool verarbeitet Ihr Bild sofort. Laden Sie die konvertierte Datei herunter, die den urspr\u00fcnglichen Dateinamen mit der neuen Erweiterung beibeh\u00e4lt. Die Konvertierung bewahrt Bildabmessungen und Metadaten, es sei denn, Sie entscheiden sich gezielt f\u00fcr deren Entfernung."
    },
    "s4": {
        "h": "Tipps und Techniken zur Stapelkonvertierung",
        "p": "Bei der Konvertierung mehrerer Bilder spart die Stapelverarbeitung erheblich Zeit. Tuttilos Bildkonverter unterst\u00fctzt Stapelkonvertierung \u2013 laden Sie einfach mehrere Dateien gleichzeitig hoch und wenden Sie dieselben Einstellungen auf alle Bilder gleichzeitig an.\n\nStellen Sie vor der Stapelkonvertierung sicher, dass alle Bilder f\u00fcr dasselbe Ausgabeformat und dieselben Qualit\u00e4tseinstellungen geeignet sind. Gruppieren Sie \u00e4hnliche Bilder: Fotografien in einem Stapel, Grafiken in einem anderen. Konvertieren Sie bei gro\u00dfen Stapeln in Gruppen von 20-30 Dateien, um Browser-Speicherprobleme zu vermeiden. Erstellen Sie vor der Konvertierung eine systematische Namenskonvention, um die Dateien geordnet zu halten. Erw\u00e4gen Sie die Verwendung konsistenter Qualit\u00e4tseinstellungen f\u00fcr zusammengeh\u00f6rige Bilder, um die visuelle Konsistenz zu wahren \u2013 besonders wichtig bei Produktfotos oder Galeriebildern."
    },
    "s5": {
        "h": "Formatspezifische Best Practices",
        "p": "F\u00fcr die JPEG-Konvertierung verwenden Sie Qualit\u00e4t 85-90 f\u00fcr hohe Qualit\u00e4tsanspr\u00fcche, 75-85 f\u00fcr Web-Nutzung und 60-75 f\u00fcr Vorschaubilder. Konvertieren Sie immer von einer hochwertigen Quelle \u2013 die Konvertierung von einem minderwertigen JPEG in ein anderes Format verbessert nicht die Qualit\u00e4t.\n\nBei der Konvertierung zu PNG verwenden Sie es f\u00fcr Bilder, die Transparenz erfordern oder Text, Logos und Strichgrafiken enthalten. PNG-Dateien sind gr\u00f6\u00dfer als JPEG, daher sollten Sie PNG f\u00fcr Fotografien vermeiden, es sei denn, Transparenz ist unerl\u00e4sslich. F\u00fcr die WebP-Konvertierung verwenden Sie Qualit\u00e4t 80-85, um JPEG-Qualit\u00e4t 90-95 bei kleineren Dateigr\u00f6\u00dfen zu erreichen. Bei der Konvertierung zu GIF bedenken Sie, dass die 256-Farben-Beschr\u00e4nkung es f\u00fcr Fotografien ungeeignet macht. SVG-Konvertierung funktioniert nur bei einfachen Grafiken \u2013 Fotografien k\u00f6nnen nicht in echtes SVG-Format konvertiert werden."
    },
    "s6": {
        "h": "Qualit\u00e4t bei der Konvertierung erhalten",
        "p": "Qualit\u00e4tserhaltung beginnt mit Ihrer Quelldatei. Konvertieren Sie immer von der h\u00f6chstm\u00f6glichen Qualit\u00e4tsquelle \u2013 erwarten Sie nie bessere Ergebnisse von einem komprimierten oder niedrig aufgel\u00f6sten Bild. Jede Konvertierung in ein verlustbehaftetes Format (JPEG, verlustbehaftetes WebP) verschlechtert die Qualit\u00e4t geringf\u00fcgig, daher minimieren Sie die Konvertierungsschritte.\n\nBei der Konvertierung zwischen verlustbehafteten Formaten summiert sich der Qualit\u00e4tsverlust. Die Konvertierung von JPEG zu WebP zu JPEG f\u00fchrt zu doppelter Komprimierung. Konvertieren Sie wenn m\u00f6glich direkt von der unkomprimierten Originalquelle. F\u00fcr Web-Nutzung konvertieren Sie einmal in Ihr Endformat, statt mehrfach zu konvertieren. Bewahren Sie die hochwertigen Originalversionen als Masterdateien auf. Wenn Sie f\u00fcr bestimmte Plattformen konvertieren, pr\u00fcfen Sie deren empfohlene Spezifikationen \u2013 viele Plattformen komprimieren hochgeladene Bilder erneut, daher verhindert ein Start mit angemessener Qualit\u00e4t unn\u00f6tige Verschlechterung."
    },
    "s7": {
        "h": "Behebung h\u00e4ufiger Konvertierungsprobleme",
        "p": "Wenn konvertierte Bilder unscharf erscheinen, haben Sie wahrscheinlich eine zu niedrige Qualit\u00e4tseinstellung verwendet oder sind von einer minderwertigen Quelle ausgegangen. Erh\u00f6hen Sie den Qualit\u00e4tsregler oder finden Sie ein besseres Quellbild. Unerwartete Dateigr\u00f6\u00dfenzunahmen treten typischerweise auf, wenn komprimierte Formate in unkomprimierte konvertiert werden \u2013 die Konvertierung von JPEG zu PNG erzeugt gr\u00f6\u00dfere Dateien, da PNG verlustfrei ist.\n\nTransparenzverlust tritt auf, wenn PNG oder WebP mit Transparenz in Formate konvertiert werden, die dies nicht unterst\u00fctzen, wie JPEG. Die transparenten Bereiche werden wei\u00df oder schwarz. W\u00e4hlen Sie PNG oder WebP als Ausgabe, um die Transparenz zu bewahren. Wenn Farben nach der Konvertierung anders aussehen, liegt m\u00f6glicherweise ein Farbprofilproblem vor. Einige Formate behandeln Farbr\u00e4ume unterschiedlich. Testen Sie bei farbkritischen Arbeiten die Konvertierungen und \u00fcberpr\u00fcfen Sie die Ergebnisse vor der Stapelverarbeitung."
    }
}

# ═══════════════════════════════════════════════
# 3. how-to-edit-pdf
# ═══════════════════════════════════════════════
de["how-to-edit-pdf"] = {
    "s1": {
        "h": "Was PDF-Bearbeitung wirklich bedeutet",
        "p": "Die PDF-Bearbeitung umfasst verschiedene Aktivit\u00e4ten, und das Verst\u00e4ndnis dieser Unterschiede hilft Ihnen, das richtige Werkzeug zu w\u00e4hlen. Echte Textbearbeitung \u2013 das \u00c4ndern des tats\u00e4chlichen Textinhalts eines PDFs \u2013 erfordert spezialisierte Software und ist komplex, da PDFs Text als positionierte Grafiken und nicht als bearbeitbare Textfl\u00fcsse speichern.\n\nH\u00e4ufiger bezieht sich PDF-Bearbeitung auf das Hinzuf\u00fcgen von Anmerkungen, Hervorhebungen, Kommentaren und Haftnotizen. Das Ausf\u00fcllen von Formularen ist eine weitere wichtige Kategorie, die das Vervollst\u00e4ndigen ausf\u00fcllbarer PDF-Formulare erm\u00f6glicht. Das Hinzuf\u00fcgen von Unterschriften, Stempeln und Bildern z\u00e4hlt ebenfalls zur PDF-Bearbeitung. Das Neuordnen, Drehen oder L\u00f6schen von Seiten gilt als strukturelle Bearbeitung. Die meisten Nutzer ben\u00f6tigen diese letztgenannten Funktionen und nicht die vollst\u00e4ndige Textbearbeitung. Tuttilos PDF-Editor konzentriert sich auf diese praktischen, allt\u00e4glichen Bearbeitungsanforderungen, die keine teure Software erfordern."
    },
    "s2": {
        "h": "PDF-Formulare online ausf\u00fcllen",
        "p": "PDF-Formulare sind allgegenw\u00e4rtig \u2013 Steuerdokumente, Antr\u00e4ge, Vertr\u00e4ge und Umfragen verwenden h\u00e4ufig das ausf\u00fcllbare PDF-Format. Traditionelles Ausf\u00fcllen von Formularen erforderte Drucken, handschriftliches Ausf\u00fcllen und Scannen. Moderne Online-Editoren wie Tuttilo rationalisieren diesen Prozess vollst\u00e4ndig.\n\nUm ein PDF-Formular mit Tuttilo auszuf\u00fcllen, laden Sie Ihr Formulardokument \u00fcber das PDF-Editor-Tool hoch. Der Editor erkennt automatisch ausf\u00fcllbare Formularfelder und erm\u00f6glicht es Ihnen, direkt in Textfelder, Kontrollk\u00e4stchen und Dropdown-Men\u00fcs zu klicken. Tippen Sie nat\u00fcrlich, wie in jedem Formular. F\u00fcr Formulare ohne vordefinierte Felder verwenden Sie das Textwerkzeug, um Text an beliebiger Stelle im Dokument hinzuzuf\u00fcgen. Sie k\u00f6nnen Schriftart, Gr\u00f6\u00dfe und Farbe anpassen, um sie an den Dokumentstil anzupassen. Nach Fertigstellung laden Sie das ausgef\u00fcllte Formular als neues PDF herunter, bereit zur Einreichung."
    },
    "s3": {
        "h": "Anmerkungen und Kommentare hinzuf\u00fcgen",
        "p": "Anmerkungen verwandeln PDFs von statischen Dokumenten in kollaborative Arbeitsbereiche. Heben Sie wichtige Passagen mit dem Textmarker-Werkzeug hervor und w\u00e4hlen Sie aus mehreren Farben zur Informationskategorisierung. F\u00fcgen Sie Textkommentare hinzu, um Bearbeitungen zu erkl\u00e4ren, Fragen zu stellen oder Feedback zu geben.\n\nDie Haftnotiz-Funktion erm\u00f6glicht das Anh\u00e4ngen erweiterbarer Notizen, die den darunterliegenden Inhalt nicht verdecken. Zeichnen Sie freih\u00e4ndig mit dem Stiftwerkzeug, um Elemente einzukreisen, Pfeile zu zeichnen oder Diagramme zu skizzieren. Verwenden Sie Formen \u2013 Rechtecke, Kreise, Pfeile \u2013 um Abschnitte hervorzuheben oder Flussdiagramme zu erstellen. Das Textfeldwerkzeug f\u00fcgt gr\u00f6\u00dfere Textbl\u00f6cke f\u00fcr ausf\u00fchrliche Kommentare hinzu. Alle Anmerkungen sind nicht-destruktiv; sie \u00fcberlagern den Originalinhalt, ohne ihn zu ver\u00e4ndern. Dies macht PDF-Anmerkungen perfekt f\u00fcr Dokumentenpr\u00fcfung, Bearbeitungsvorschl\u00e4ge und kollaboratives Feedback."
    },
    "s4": {
        "h": "PDF-Dokumente elektronisch unterschreiben",
        "p": "Elektronische Unterschriften haben in den meisten Rechtsordnungen rechtliche G\u00fcltigkeit und machen den Druck-Unterschrift-Scan-Workflow \u00fcberfl\u00fcssig. Tuttilos PDF-Editor bietet mehrere Signaturmethoden f\u00fcr verschiedene Bed\u00fcrfnisse und Vorlieben.\n\nMit der Option \u201eUnterschrift zeichnen\u201c k\u00f6nnen Sie mit Maus, Trackpad oder Touchscreen unterschreiben und handschriftliche Unterschriften nachahmen. Die Funktion \u201eUnterschrift tippen\u201c erstellt eine Signatur aus Text mithilfe von Schreibschrift-Schriftarten, die Handschrift \u00e4hneln. \u201eUnterschrift hochladen\u201c erm\u00f6glicht das Fotografieren Ihrer handschriftlichen Unterschrift und das Einf\u00fcgen als Bild. Einmal erstellt, k\u00f6nnen Unterschriften in der Gr\u00f6\u00dfe angepasst und beliebig im Dokument positioniert werden. Sie k\u00f6nnen h\u00e4ufig verwendete Unterschriften f\u00fcr schnelles Einf\u00fcgen in mehreren Dokumenten speichern. F\u00fcgen Sie Daten, Initialen und Firmenstempel auf die gleiche Weise hinzu. Heruntergeladene PDFs behalten alle Unterschriften dauerhaft bei."
    },
    "s5": {
        "h": "Arbeiten mit Bildern und Stempeln",
        "p": "Das Hinzuf\u00fcgen von Bildern zu PDFs dient vielen Zwecken \u2013 Logos f\u00fcr die Markenbildung, Fotos f\u00fcr Berichte, Stempel f\u00fcr Genehmigungen oder Wasserzeichen zum Schutz. Tuttilos Bildeinf\u00fcge-Tool unterst\u00fctzt g\u00e4ngige Formate einschlie\u00dflich JPEG, PNG und SVG.\n\nLaden Sie Bilder von Ihrem Ger\u00e4t hoch oder ziehen Sie sie direkt in den Editor. \u00c4ndern Sie die Bildgr\u00f6\u00dfe durch Ziehen an den Ecken bei Beibehaltung des Seitenverh\u00e4ltnisses. Positionieren Sie Bilder pr\u00e4zise durch Drag-and-Drop oder Pfeiltasten f\u00fcr die Feinabstimmung. Schichten Sie Bilder \u00fcber oder unter Text und andere Elemente. H\u00e4ufige Anwendungsf\u00e4lle umfassen das Hinzuf\u00fcgen von Firmenlogos zu Rechnungen, das Einf\u00fcgen von Diagrammen in Berichte, das Platzieren von Genehmigungsstempeln auf gepr\u00fcften Dokumenten und das Hinzuf\u00fcgen von Profilfotos zu Bewerbungen. Sie k\u00f6nnen auch Text-Wasserzeichen f\u00fcr Entwurfsversionen oder Vertraulichkeitsmarkierungen hinzuf\u00fcgen."
    },
    "s6": {
        "h": "Datenschutz und Sicherheitsaspekte",
        "p": "Bei der Bearbeitung sensibler Dokumente wie Vertr\u00e4ge, Finanzberichte oder pers\u00f6nliche Antr\u00e4ge ist Sicherheit wichtig. Viele Online-PDF-Editoren laden Ihre Dateien zur Verarbeitung auf Server hoch, was Datenschutzrisiken und Compliance-Probleme verursacht.\n\nTuttilos PDF-Editor verarbeitet alles direkt in Ihrem Browser mithilfe von clientseitigem JavaScript. Ihr PDF wird nie auf einen Server hochgeladen \u2013 es bleibt w\u00e4hrend des gesamten Bearbeitungsprozesses auf Ihrem Ger\u00e4t. Dieser Ansatz gew\u00e4hrleistet vollst\u00e4ndige Privatsph\u00e4re und funktioniert offline, sobald die Seite geladen ist. Ihre Bearbeitungen werden sofort verarbeitet, ohne auf Serverantworten warten zu m\u00fcssen. Es gibt keine Dateigr\u00f6\u00dfenbeschr\u00e4nkungen jenseits der Speicherkapazit\u00e4t Ihres Ger\u00e4ts. Diese clientseitige Architektur entspricht Datenschutzvorschriften wie DSGVO und HIPAA. Wenn Sie den Browser-Tab schlie\u00dfen, verbleibt keine Spur Ihres Dokuments auf irgendeinem Server, da es von vornherein nie hochgeladen wurde."
    }
}

# ═══════════════════════════════════════════════
# 4. how-to-remove-background
# ═══════════════════════════════════════════════
de["how-to-remove-background"] = {
    "s1": {
        "h": "Warum Hintergrundentfernung wichtig ist",
        "p": "Die Hintergrundentfernung ist in verschiedenen Branchen und Anwendungsf\u00e4llen unverzichtbar geworden. E-Commerce-Unternehmen ben\u00f6tigen saubere Produktfotos mit transparenten Hintergr\u00fcnden, um Marktplatz-Anforderungen zu erf\u00fcllen und professionelle Angebote zu erstellen. Amazon, eBay und die meisten Plattformen verlangen wei\u00dfe oder transparente Hintergr\u00fcnde f\u00fcr prim\u00e4re Produktbilder.\n\nSocial-Media-Content-Creator entfernen Hintergr\u00fcnde, um auffallende Beitr\u00e4ge, professionelle Portr\u00e4tfotos und gebrandete Grafiken zu erstellen. Marketing-Teams nutzen die Hintergrundentfernung f\u00fcr Werbung, Pr\u00e4sentationen und Werbematerialien. Designer ben\u00f6tigen saubere Ausschnitte f\u00fcr Kompositionen, Collagen und Grafikdesign-Projekte. Immobilienmakler entfernen st\u00f6rende Hintergr\u00fcnde aus Immobilienfotos. Profilbilder f\u00fcr professionelle Netzwerke wie LinkedIn profitieren von sauberen, ablenkungsfreien Hintergr\u00fcnden. Was einst teure Software und professionelle F\u00e4higkeiten erforderte, ist jetzt in Sekunden mit KI-gest\u00fctzten Tools wie Tuttilo erreichbar."
    },
    "s2": {
        "h": "Wie KI-Hintergrundentfernung funktioniert",
        "p": "Moderne Hintergrundentfernung basiert auf ausgefeilten Machine-Learning-Algorithmen, die mit Millionen von Bildern trainiert wurden. Diese KI-Modelle lernen, Vordergrundmotive von Hintergr\u00fcnden zu unterscheiden, indem sie Muster, Kanten, Texturen und semantische Bedeutung erkennen.\n\nDer Prozess beginnt damit, dass die KI Ihr Bild analysiert, um das Hauptmotiv zu identifizieren \u2013 ob Person, Produkt, Tier oder Objekt. Fortschrittliche Algorithmen erkennen feine Kanten wie Haarstr\u00e4hnen, Fell oder transparente Materialien, bei denen herk\u00f6mmliche Auswahlwerkzeuge Schwierigkeiten haben. Die KI weist jedem Pixel Konfidenzwerte zu und bestimmt, ob es zum Motiv oder zum Hintergrund geh\u00f6rt. Als Hintergrund identifizierte Pixel werden entfernt oder transparent gemacht. Der gesamte Vorgang dauert Millisekunden und liefert Ergebnisse, f\u00fcr die manuelle Bearbeitung Stunden br\u00e4uchte. Tuttilos Hintergrundentferner verwendet modernste Modelle, die f\u00fcr Genauigkeit bei verschiedensten Bildtypen optimiert sind."
    },
    "s3": {
        "h": "Schritt-f\u00fcr-Schritt-Hintergrundentfernung mit Tuttilo",
        "p": "Das Entfernen von Hintergr\u00fcnden mit Tuttilo erfordert keine Designerfahrung oder technisches Wissen. Navigieren Sie zu tuttilo.com und w\u00e4hlen Sie das Hintergrundentferner-Tool aus der Kategorie Bilder. Laden Sie Ihr Bild hoch, indem Sie auf den Upload-Bereich klicken oder Ihr Foto direkt in den Browser ziehen.\n\nDie KI verarbeitet Ihr Bild automatisch und ben\u00f6tigt je nach Bildgr\u00f6\u00dfe und Komplexit\u00e4t typischerweise 2-5 Sekunden. Das Tool zeigt das Ergebnis mit einem transparenten Schachbrettmuster an, das die entfernten Bereiche kennzeichnet. \u00dcberpr\u00fcfen Sie den Ausschnitt sorgf\u00e4ltig und zoomen Sie hinein, um Kanten und feine Details zu pr\u00fcfen. Falls das Ergebnis eine Nachbesserung ben\u00f6tigt, verwenden Sie die manuellen Korrekturwerkzeuge, um versehentlich entfernte Bereiche wiederherzustellen oder verbleibende Hintergrundfragmente zu beseitigen. Laden Sie Ihr Bild im PNG-Format herunter, um die Transparenz zu bewahren, oder w\u00e4hlen Sie eine Hintergrundfarbe, falls f\u00fcr bestimmte Plattformanforderungen n\u00f6tig."
    },
    "s4": {
        "h": "Tipps f\u00fcr saubere, professionelle Ergebnisse",
        "p": "Die Bildqualit\u00e4t beeinflusst die Ergebnisse der Hintergrundentfernung erheblich. Beginnen Sie wann immer m\u00f6glich mit hochaufl\u00f6senden Fotos \u2013 mindestens 1000 Pixel an der l\u00e4ngsten Seite f\u00fcr beste Ergebnisse. Stellen Sie eine gute Beleuchtung mit klarer Unterscheidung zwischen Motiv und Hintergrund sicher. Scharfe, fokussierte Bilder erzeugen sauberere Ausschnitte als unscharfe Fotos.\n\nFotos mit einfachen Hintergr\u00fcnden lassen sich sauberer freistellen als solche mit unruhigen, \u00fcberladenen Hintergr\u00fcnden. Einfarbige Hintergr\u00fcnde sind ideal, aber nicht zwingend erforderlich. Stellen Sie ausreichend Kontrast zwischen Motiv und Hintergrund sicher \u2013 das Fotografieren eines wei\u00dfen Produkts auf wei\u00dfem Hintergrund stellt selbst f\u00fcr KI eine Herausforderung dar. F\u00fcr Portr\u00e4ts richten Sie das Motiv zum Licht aus, um \u00fcberm\u00e4\u00dfige Schatten zu vermeiden. Wenn Sie Produktfotos speziell f\u00fcr die Hintergrundentfernung aufnehmen, verwenden Sie einen schlichten Hintergrund und vermeiden Sie Schatten. Bei komplexen Motiven wie Haaren oder Fell \u00fcberbelichten Sie den Hintergrund leicht, um mehr Trennung zu erzeugen."
    },
    "s5": {
        "h": "H\u00e4ufige Anwendungsf\u00e4lle und Einsatzbereiche",
        "p": "E-Commerce-Verk\u00e4ufer nutzen die Hintergrundentfernung, um konsistente Produktkataloge zu erstellen. Entfernen Sie den Hintergrund, f\u00fcgen Sie einen reinwei\u00dfen oder transparenten Hintergrund hinzu, und Ihre Produkte erf\u00fcllen die Marktplatz-Standards. Erstellen Sie Lifestyle-Variationen, indem Sie Produkte auf verschiedenen Hintergrundszenen platzieren.\n\nContent-Creator gestalten individuelle Vorschaubilder, Social-Media-Grafiken und Werbematerialien. Entfernen Sie Ihren Portr\u00e4thintergrund und platzieren Sie sich vor gebrandeten Hintergr\u00fcnden oder Landschaftsbildern. Designer erstellen Kompositionen, indem sie Elemente aus mehreren Fotos kombinieren. Immobilienmakler entfernen bedeckte Himmel und ersetzen sie durch Hintergr\u00fcnde mit blauem Himmel. Arbeitssuchende erstellen professionelle Portr\u00e4tfotos aus Freizeitfotos, indem sie unordentliche oder st\u00f6rende Hintergr\u00fcnde entfernen. Eventfotografen bieten Kunden freigestellte Fotos f\u00fcr personalisierte Produkte wie Tassen und T-Shirts an."
    },
    "s6": {
        "h": "Fehlerbehebung und Verfeinerungstechniken",
        "p": "Wenn die KI Teile Ihres Motivs entfernt, hat das Bild wahrscheinlich einen niedrigen Kontrast oder das Motiv verschmilzt mit dem Hintergrund. Versuchen Sie, Helligkeit und Kontrast vor der Entfernung anzupassen, oder verwenden Sie manuelle Verfeinerungswerkzeuge, um entfernte Bereiche wiederherzustellen. Wenn Hintergrundreste verbleiben, zoomen Sie hinein und verwenden Sie das Radiergummi-Werkzeug, um Kanten manuell zu s\u00e4ubern.\n\nBei komplexen Haaren oder Fell, durch die der Hintergrund durchscheint, versuchen Sie die Kantenverfeinerungsfunktion, falls verf\u00fcgbar, oder akzeptieren Sie, dass gewisse Komplexit\u00e4t nat\u00fcrlich ist. Perfekt saubere Haarkanten erfordern professionelle Retusche. Wenn das gesamte Ergebnis falsch aussieht, stellen Sie sicher, dass Ihr Motiv deutlich der Hauptfokus des Bildes ist \u2013 unruhige Fotos mit mehreren Motiven verwirren die KI. Bei transparenten oder Glasobjekten entfernt die KI diese oft vollst\u00e4ndig, da sie dem Hintergrund \u00e4hneln. Diese Motive erfordern m\u00f6glicherweise manuelle Bearbeitungstechniken jenseits der automatischen Entfernung.\n\nWenn Kanten zu scharf oder k\u00fcnstlich erscheinen, wenden Sie eine ganz leichte Weichzeichnung an, um nat\u00fcrlich aussehende \u00dcberg\u00e4nge zu erzeugen. Bei Produkten mit feinen Details wie Schmuck oder Spitze \u00fcberpr\u00fcfen Sie die Ergebnisse bei 100% Zoom, um sicherzustellen, dass Details erhalten bleiben."
    }
}

# Write part1 and continue in part2 script
with open('/tmp/de_blog_part1.json', 'w', encoding='utf-8') as f:
    json.dump(de, f, ensure_ascii=False)
print(f"Part 1: {len(de)} articles written")
