#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json

with open('/tmp/de_blog_part1.json', 'r', encoding='utf-8') as f:
    de = json.load(f)

# 5. how-to-create-qr-code
de["how-to-create-qr-code"] = {
    "s1": {
        "h": "QR-Code-Typen verstehen",
        "p": "QR-Codes speichern je nach Verwendungszweck verschiedene Arten von Informationen. URL-QR-Codes, der h\u00e4ufigste Typ, verlinken beim Scannen auf Websites. Codieren Sie einfach eine beliebige Webadresse und Nutzer k\u00f6nnen sie mit einem einzigen Scan besuchen \u2013 kein Tippen n\u00f6tig. WLAN-QR-Codes enthalten Netzwerk-Zugangsdaten, sodass G\u00e4ste sich ohne manuelle Passworteingabe mit Ihrem Netzwerk verbinden k\u00f6nnen.\n\nKontaktkarten-QR-Codes (vCard) speichern vollst\u00e4ndige Kontaktinformationen einschlie\u00dflich Name, Telefon, E-Mail, Adresse und Firmendaten. Das Scannen erstellt automatisch einen neuen Kontakt auf dem Telefon des Nutzers. Text-QR-Codes enthalten einfache Nachrichten, die beim Scannen angezeigt werden. E-Mail-QR-Codes erstellen vorausgef\u00fcllte E-Mail-Entw\u00fcrfe mit Empf\u00e4nger, Betreff und Nachricht. SMS-QR-Codes verfassen Textnachrichten an bestimmte Nummern. Telefonnummer-QR-Codes l\u00f6sen beim Scannen Anrufe aus. Standort-QR-Codes \u00f6ffnen Kartenanwendungen an bestimmten Koordinaten. Jeder Typ dient unterschiedlichen Zwecken, und Tuttilos QR-Code-Generator unterst\u00fctzt alle g\u00e4ngigen Formate."
    },
    "s2": {
        "h": "Ihren ersten QR-Code mit Tuttilo erstellen",
        "p": "Das Generieren eines QR-Codes mit Tuttilo dauert Sekunden und erfordert keine technischen Kenntnisse. Besuchen Sie tuttilo.com und navigieren Sie zum QR-Code-Generator in der Kategorie Werkzeuge. W\u00e4hlen Sie den gew\u00fcnschten QR-Code-Typ aus dem Dropdown-Men\u00fc \u2013 URL, WLAN, Kontaktkarte, Text, E-Mail oder SMS.\n\nGeben Sie die relevanten Informationen in die Eingabefelder ein. F\u00fcr URLs f\u00fcgen Sie die vollst\u00e4ndige Webadresse einschlie\u00dflich https:// ein. F\u00fcr WLAN-Codes geben Sie Ihren Netzwerknamen (SSID), das Passwort ein und w\u00e4hlen den Sicherheitstyp (WPA, WEP oder keiner). F\u00fcr Kontaktkarten f\u00fcllen Sie die verf\u00fcgbaren Felder aus \u2013 Name, Telefon, E-Mail, Organisation und Adresse. Nach Eingabe Ihrer Informationen wird der QR-Code automatisch generiert. Laden Sie den Code als PNG- oder SVG-Format herunter. PNG eignet sich f\u00fcr die meisten Zwecke, w\u00e4hrend SVG vektorielle Skalierbarkeit f\u00fcr professionellen Druck bietet."
    },
    "s3": {
        "h": "Anpassungsoptionen und Branding",
        "p": "Moderne QR-Codes gehen \u00fcber einfache schwarz-wei\u00dfe Quadrate hinaus. Individualisierung hilft dabei, QR-Codes an Ihre Markenidentit\u00e4t anzupassen und mehr Scans zu erzielen. Farbanpassung erm\u00f6glicht das \u00c4ndern von Vordergrund- und Hintergrundfarben. Behalten Sie einen hohen Kontrast bei \u2013 dunkler Vordergrund auf hellem Hintergrund gew\u00e4hrleistet zuverl\u00e4ssiges Scannen.\n\nViele Generatoren, einschlie\u00dflich Tuttilo, erlauben das Hinzuf\u00fcgen von Logos oder Bildern in der QR-Code-Mitte. Das Logo sollte nicht mehr als 20-30% der Gesamtcodefl\u00e4che einnehmen, um die Scannbarkeit zu erhalten. QR-Codes enthalten Fehlerkorrektur, sodass sie auch bei teilweise verdeckten Bereichen funktionieren \u2013 diese Eigenschaft erm\u00f6glicht die Logo-Einbettung. Passen Sie die Eckmuster und Datenpunkt-Stile f\u00fcr ein unverwechselbares Erscheinungsbild an. Runde Punkte statt quadratischer Pixel erzeugen eine weichere, modernere \u00c4sthetik. Rahmen Sie Ihren QR-Code mit einem Rand und f\u00fcgen Sie einen Call-to-Action-Text wie \u201eScannen Sie mich\u201c oder \u201eBesuchen Sie unsere Website\u201c hinzu, um die Scan-Rate zu erh\u00f6hen."
    },
    "s4": {
        "h": "QR-Code-Anwendungsf\u00e4lle und Einsatzbereiche",
        "p": "Visitenkarten mit QR-Codes speichern Kontakte sofort \u2013 kein m\u00fchsames Eintippen von Informationen von Papierkarten mehr. F\u00fcgen Sie einen vCard-QR-Code zu Ihrer Karte, E-Mail-Signatur oder Website hinzu. Restaurants nutzen QR-Codes f\u00fcr digitale Speisekarten, wodurch die Kosten f\u00fcr gedruckte Men\u00fcs entfallen und sofortige Aktualisierungen m\u00f6glich werden.\n\nProduktverpackungen enthalten QR-Codes, die zu Produktinformationen, Anleitungen, Garantieregistrierung und Kundensupport f\u00fchren. Eintrittskarten nutzen zunehmend QR-Codes f\u00fcr kontaktloses Einchecken und Validierung. Marketingmaterialien wie Poster, Flyer und Werbeanzeigen verwenden QR-Codes, um Besucher von physischen zu digitalen R\u00e4umen zu leiten. Immobilienschilder enthalten QR-Codes, die zu virtuellen Rundg\u00e4ngen und Objektdetails verlinken. Museen und Galerien bieten QR-Codes f\u00fcr Audioguides und erweiterte Informationen. Produktauthentifizierung nutzt einzigartige QR-Codes zur \u00dcberpr\u00fcfung der Echtheit. Zahlungssysteme wie PayPal und Kryptow\u00e4hrungs-Wallets verwenden QR-Codes zur Transaktionseinleitung."
    },
    "s5": {
        "h": "Best Practices f\u00fcr das Drucken von QR-Codes",
        "p": "Die Druckqualit\u00e4t beeinflusst die Scannbarkeit direkt. Verwenden Sie hochaufl\u00f6sende Bilder \u2013 mindestens 300 DPI f\u00fcr Druck, und skalieren Sie niemals niedrig aufgel\u00f6ste Codes hoch. Laden Sie das SVG-Format f\u00fcr professionellen Druck herunter, da Vektorformate unbegrenzt ohne Qualit\u00e4tsverlust skalieren. Beachten Sie die Mindestgr\u00f6\u00dfenanforderungen: 2\u00d72 cm f\u00fcr nahes Scannen, gr\u00f6\u00dfer f\u00fcr Fernscannen.\n\nStellen Sie eine ausreichende Ruhezone sicher \u2013 der wei\u00dfe Rand um den QR-Code sollte mindestens vier Module (das Vierfache der Breite der kleinsten Quadrate) breit sein. Testen Sie gedruckte Codes vor der Massenproduktion mit mehreren Ger\u00e4ten und Scan-Apps. Matte Oberfl\u00e4chen scannen zuverl\u00e4ssiger als gl\u00e4nzende Oberfl\u00e4chen, die Reflexionen verursachen. Vermeiden Sie das Platzieren von QR-Codes auf gekr\u00fcmmten, geknitterten oder strukturierten Oberfl\u00e4chen, die das Muster verzerren. F\u00fcr den Au\u00dfeneinsatz verhindern witterungsbest\u00e4ndige Materialien und UV-resistente Tinten das Verblassen. Beachten Sie die Platzierungsh\u00f6he \u2013 Codes sollten in bequemer Scanh\u00f6he angebracht sein, typischerweise auf Brust- bis Augenh\u00f6he."
    },
    "s6": {
        "h": "Testen und Verfolgen der QR-Code-Performance",
        "p": "Testen Sie QR-Codes immer vor der Verteilung. Scannen Sie mit mehreren Ger\u00e4ten unter iOS und Android, um die plattform\u00fcbergreifende Kompatibilit\u00e4t sicherzustellen. Testen Sie unter verschiedenen Lichtbedingungen \u2013 helles Sonnenlicht kann Blendung verursachen, w\u00e4hrend schwaches Licht die Kamerafokussierung verhindern kann. \u00dcberpr\u00fcfen Sie, dass die codierten Informationen korrekt sind, indem Sie pr\u00fcfen, wohin gescannte Codes f\u00fchren.\n\nF\u00fcr gesch\u00e4ftliche Anwendungen sollten Sie dynamische QR-Codes in Betracht ziehen, die das \u00c4ndern der Ziel-URL ohne Neudruck des Codes erm\u00f6glichen. W\u00e4hrend Tuttilo statische Codes generiert, bieten Drittanbieterdienste dynamische Codes mit Analyse-Tracking. Verfolgen Sie, wie oft Codes gescannt werden, wann, wo und von welchen Ger\u00e4ten. Diese Daten helfen bei der Messung der Kampagneneffektivit\u00e4t. \u00dcberpr\u00fcfen Sie bei langfristiger Nutzung regelm\u00e4\u00dfig, ob verlinkte Inhalte noch erreichbar sind \u2013 defekte Links frustrieren Nutzer. \u00dcberwachen Sie Analysen, um Engagement-Muster zu verstehen und Platzierung sowie Design entsprechend zu optimieren."
    }
}

# 6. how-to-convert-video
de["how-to-convert-video"] = {
    "s1": {
        "h": "Wann Videokonvertierung n\u00f6tig ist",
        "p": "Die Konvertierung von Videoformaten l\u00f6st zahlreiche praktische Probleme. Ger\u00e4tekompatibilit\u00e4t ist der h\u00e4ufigste Grund \u2013 ein Video, das auf Ihrem Computer einwandfrei abgespielt wird, funktioniert m\u00f6glicherweise nicht auf Ihrem Smartphone, Tablet oder Smart-TV. Jedes Ger\u00e4t unterst\u00fctzt unterschiedliche Codec-Kombinationen und Container-Formate.\n\nWeb-Optimierung erfordert die Konvertierung in Formate, die Qualit\u00e4t und Dateigr\u00f6\u00dfe ausbalancieren. Websites verlangen kleinere Dateien f\u00fcr schnelleres Laden und bevorzugen typischerweise MP4 mit H.264-Codierung. Social-Media-Plattformen haben spezifische Formatanforderungen \u2013 Instagram bevorzugt MP4, w\u00e4hrend einige Plattformen WebM oder MOV akzeptieren. Kompatibilit\u00e4tsprobleme mit Schnittsoftware entstehen, wenn Ihr Editor Ihr Quellformat nicht unterst\u00fctzt. Legacy-Systeme und \u00e4ltere Ger\u00e4te erfordern m\u00f6glicherweise die Konvertierung in veraltete Formate. Speicher\u00fcberlegungen treiben die Konvertierung in effizienter komprimierte Formate voran. E-Mail- und Messaging-Apps haben Gr\u00f6\u00dfenbeschr\u00e4nkungen, die eine Konvertierung in kleinere Formate erfordern."
    },
    "s2": {
        "h": "G\u00e4ngige Videoformate erkl\u00e4rt",
        "p": "MP4 (MPEG-4) dominiert die moderne Videodistribution dank hervorragender Komprimierung, breiter Kompatibilit\u00e4t und hoher Qualit\u00e4t. Es ist das Standardformat f\u00fcr Web-Video, Social Media und mobile Ger\u00e4te. WebM, von Google entwickelt, bietet \u00fcberlegene Komprimierung f\u00fcr Web-Nutzung und ist Open-Source, jedoch weniger universell kompatibel als MP4.\n\nAVI (Audio Video Interleave) ist ein \u00e4lteres Microsoft-Format, das gro\u00dfe Dateien erzeugt, aber breite Kompatibilit\u00e4t bietet, besonders mit Windows-Systemen. MOV, Apples QuickTime-Format, funktioniert hervorragend auf macOS und iOS, kann aber auf anderen Plattformen Kompatibilit\u00e4tsprobleme haben. MKV (Matroska) ist ein flexibler Container, der mehrere Audiospuren, Untertitel und hochwertige Videos unterst\u00fctzt und f\u00fcr HD-Inhalte und Filme bevorzugt wird. FLV (Flash Video) war einst f\u00fcr Web-Video dominant, ist aber mittlerweile weitgehend veraltet. WMV (Windows Media Video) ist f\u00fcr Windows-Systeme optimiert, aber anderswo weniger kompatibel."
    },
    "s3": {
        "h": "Schritt-f\u00fcr-Schritt-Videokonvertierung mit Tuttilo",
        "p": "Das Konvertieren von Videos mit Tuttilo ist unkompliziert und erfolgt f\u00fcr vollst\u00e4ndige Privatsph\u00e4re komplett in Ihrem Browser. Navigieren Sie zu tuttilo.com und w\u00e4hlen Sie das Videokonverter-Tool aus der Kategorie Video. Laden Sie Ihre Videodatei hoch, indem Sie auf den Upload-Bereich klicken oder die Datei direkt in das Browserfenster ziehen.\n\nW\u00e4hlen Sie Ihr gew\u00fcnschtes Ausgabeformat aus dem Dropdown-Men\u00fc \u2013 MP4, WebM, AVI, MOV oder andere je nach Bedarf. W\u00e4hlen Sie Qualit\u00e4tseinstellungen: hohe Qualit\u00e4t f\u00fcr Archivierung oder Bearbeitung, mittel f\u00fcr allgemeine Nutzung und Web, oder niedrig f\u00fcr maximale Komprimierung und kleine Dateigr\u00f6\u00dfen. Passen Sie bei Bedarf die Aufl\u00f6sung an \u2013 eine Verkleinerung von 4K auf 1080p oder 720p reduziert die Dateigr\u00f6\u00dfe erheblich. Klicken Sie auf \u201eKonvertieren\u201c und die Verarbeitung beginnt. Die Konvertierungszeit variiert je nach Dateigr\u00f6\u00dfe, gew\u00e4hltem Format und Rechenleistung Ihres Ger\u00e4ts. Laden Sie die konvertierte Datei nach Abschluss herunter."
    },
    "s4": {
        "h": "Das richtige Ausgabeformat w\u00e4hlen",
        "p": "Die Formatwahl h\u00e4ngt vom geplanten Verwendungszweck ab. F\u00fcr Web-Videos und Social Media w\u00e4hlen Sie MP4 mit H.264-Codec f\u00fcr maximale Kompatibilit\u00e4t und angemessene Dateigr\u00f6\u00dfe. Stellen Sie die Aufl\u00f6sung auf 1080p oder 720p ein, es sei denn, 4K wird ausdr\u00fccklich ben\u00f6tigt. Eine Qualit\u00e4tseinstellung von 75-85% liefert hervorragende Ergebnisse.\n\nF\u00fcr Archivierung oder Bearbeitung verwenden Sie Formate mit minimaler Komprimierung wie AVI oder hochqualitatives MP4, um maximale Details zu bewahren. Wenn Sie Inhalte f\u00fcr Apple-Ger\u00e4te erstellen oder in Final Cut Pro bearbeiten, ist MOV optimal. F\u00fcr Kompatibilit\u00e4t mit \u00e4lteren Windows-Systemen oder Legacy-Software ist AVI zuverl\u00e4ssig trotz gr\u00f6\u00dferer Dateigr\u00f6\u00dfen. Wenn die Dateigr\u00f6\u00dfe entscheidend ist \u2013 E-Mail-Anh\u00e4nge oder begrenzter Speicher \u2013 verwenden Sie WebM oder stark komprimiertes MP4 mit niedrigerer Aufl\u00f6sung. F\u00fcr Videos mit mehreren Audiospuren oder Untertiteloptionen bewahrt MKV alle Spuren intakt."
    },
    "s5": {
        "h": "Dateigr\u00f6\u00dfe ohne Qualit\u00e4tsverlust optimieren",
        "p": "Die Videodateigr\u00f6\u00dfe h\u00e4ngt von Aufl\u00f6sung, Bitrate, Codec und Dauer ab. Die Reduzierung der Aufl\u00f6sung von 4K auf 1080p reduziert die Dateigr\u00f6\u00dfe um etwa 75% bei minimalem wahrgenommenem Qualit\u00e4tsverlust auf den meisten Bildschirmen. Moderne Codecs wie H.265 (HEVC) erzielen 40-50% bessere Komprimierung als H.264 bei gleicher Qualit\u00e4t, obwohl die Kompatibilit\u00e4t etwas eingeschr\u00e4nkter ist.\n\nDie Bitrate steuert Qualit\u00e4t und Dateigr\u00f6\u00dfe direkt. Variable Bitrate (VBR) bietet ein besseres Qualit\u00e4t-zu-Gr\u00f6\u00dfe-Verh\u00e4ltnis als konstante Bitrate (CBR), indem sie komplexen Szenen mehr Bits und einfachen Szenen weniger zuweist. Die Reduzierung der Bildrate von 60fps auf 30fps halbiert die zeitlichen Daten ohne sp\u00fcrbaren Qualit\u00e4tsverlust bei den meisten Inhalten. Schneiden Sie unn\u00f6tige Abschnitte vor der Konvertierung \u2013 das Entfernen von Intro-/Outro-Segmenten reduziert die Dateigr\u00f6\u00dfe proportional. Zwei-Pass-Codierung erzeugt bessere Qualit\u00e4t bei gleicher Dateigr\u00f6\u00dfe im Vergleich zu Ein-Pass-Codierung, dauert aber l\u00e4nger."
    },
    "s6": {
        "h": "H\u00e4ufige Konvertierungsfehler vermeiden",
        "p": "Konvertieren Sie nie wiederholt zwischen verlustbehafteten Formaten. Jede Konvertierung f\u00fchrt zu zus\u00e4tzlicher Qualit\u00e4tsverschlechterung durch Generationsverlust. Die Konvertierung von MP4 zu AVI zu WebM zu MP4 erzeugt schreckliche Ergebnisse. Konvertieren Sie nur einmal von der h\u00f6chsten verf\u00fcgbaren Qualit\u00e4tsquelle.\n\nSkalieren Sie die Aufl\u00f6sung nicht hoch \u2013 die Konvertierung von 720p zu 4K f\u00fcgt keine Details hinzu, sie vergr\u00f6\u00dfert nur die Datei. Behalten Sie die Aufl\u00f6sung bei oder reduzieren Sie sie w\u00e4hrend der Konvertierung. Vermeiden Sie extreme Komprimierung bei Videos, die Sie weiter bearbeiten m\u00f6chten; das Bearbeiten komprimierter Videos verst\u00e4rkt den Qualit\u00e4tsverlust. Konvertieren Sie nicht, ohne vorher ein kurzes Sample zu testen, besonders bei unbekannten Einstellungen. Ein einst\u00fcndiges Video zu konvertieren, nur um Inkompatibilit\u00e4t festzustellen, verschwendet Zeit. Bewahren Sie Originaldateien als Sicherungskopien auf, bevor Sie sie l\u00f6schen \u2013 wenn das Konvertierungsergebnis unbefriedigend ist, k\u00f6nnen Sie mit anderen Einstellungen erneut versuchen. Bedenken Sie, dass Konvertierung immer Zeit braucht; l\u00e4ngere Videos und h\u00f6here Qualit\u00e4tseinstellungen erfordern Geduld."
    }
}

# 7. how-to-merge-pdf
de["how-to-merge-pdf"] = {
    "s1": {
        "h": "Warum PDF-Dateien zusammenf\u00fchren",
        "p": "Das Zusammenf\u00fchren von PDFs l\u00f6st zahlreiche organisatorische und praktische Herausforderungen. Das Kombinieren mehrerer gescannter Dokumente in einer einzigen Datei vereinfacht die Speicherung und das Teilen. Statt f\u00fcnf separate Anh\u00e4nge per E-Mail zu senden, verschicken Sie eine konsolidierte Datei, die Empf\u00e4nger leicht verwalten k\u00f6nnen.\n\nProjektdokumentation verteilt sich oft \u00fcber mehrere Dateien \u2013 Berichte, Rechnungen, Vertr\u00e4ge und Begleitmaterialien. Das Zusammenf\u00fchren erstellt umfassende Projektpakete. Studierende kombinieren Aufgabenkomponenten, Forschungsartikel und Notizen zu einzelnen Abgabedateien. Juristen stellen Fallakten, Beweismittel und Korrespondenz zu organisierten Fallakten zusammen. Verwaltungsaufgaben wie Spesenabrechnungen profitieren vom Zusammenf\u00fchren von Belegen und Dokumentation zu einzelnen Erstattungspaketen. Digitale Archivierung wird handhabbarer, wenn zusammengeh\u00f6rige Dokumente zu thematischen Sammlungen zusammengef\u00fchrt werden. Bewerbungen wirken professioneller, wenn Lebenslauf, Portfolio und Referenzen in einem PDF vereint werden."
    },
    "s2": {
        "h": "Schritt-f\u00fcr-Schritt-PDF-Zusammenf\u00fchrung mit Tuttilo",
        "p": "Das Zusammenf\u00fchren von PDFs mit Tuttilo ist intuitiv und sicher \u2013 es geschieht vollst\u00e4ndig in Ihrem Browser. Besuchen Sie tuttilo.com und navigieren Sie zum PDF-Zusammenf\u00fchrungstool in der Kategorie Dokumente. Laden Sie Ihre PDF-Dateien hoch, indem Sie auf den Upload-Bereich klicken oder mehrere Dateien gleichzeitig in das Browserfenster ziehen.\n\nDas Tool zeigt Vorschaubilder aller hochgeladenen Dateien in der von Ihnen gew\u00e4hlten Reihenfolge an. Ordnen Sie Dateien durch Ziehen der Vorschaubilder in Ihre bevorzugte Reihenfolge \u2013 dies bestimmt die endg\u00fcltige Seitenreihenfolge im zusammengef\u00fchrten Dokument. \u00dcberpr\u00fcfen Sie die Reihenfolge sorgf\u00e4ltig vor dem Fortfahren und stellen Sie einen logischen Ablauf sicher. Klicken Sie auf \u201ePDFs zusammenf\u00fchren\u201c und das Tool kombiniert alle Dateien zu einem Dokument. Der Zusammenf\u00fchrungsprozess ist typischerweise in Sekunden abgeschlossen, selbst bei Dutzenden von Dateien. Laden Sie das zusammengef\u00fchrte PDF herunter oder benennen Sie es vor dem Speichern um. Ihre Originaldateien bleiben unver\u00e4ndert."
    },
    "s3": {
        "h": "Strategien und Tipps zur Seitenreihenfolge",
        "p": "Durchdachte Seitenreihenfolge erstellt professionelle, logische Dokumente. F\u00fcr chronologische Sammlungen wie Besprechungsnotizen oder Projektzeitpl\u00e4ne ordnen Sie Dateien nach Datum. Viele Tools, einschlie\u00dflich Tuttilo, erlauben die Sortierung nach Dateinamen \u2013 die Verwendung datierter Dateinamen (JJJJ-MM-TT-Format) erm\u00f6glicht automatische chronologische Sortierung.\n\nF\u00fcr hierarchische Dokumente wie Berichte platzieren Sie die Zusammenfassung zuerst, gefolgt vom Hauptinhalt, dann Anh\u00e4nge und Begleitmaterialien. Beim Zusammenf\u00fchren von Vertr\u00e4gen und Vereinbarungen positionieren Sie die Hauptvereinbarung zuerst, dann Zeitpl\u00e4ne, Anlagen und Unterschriften. F\u00fcr Lehrmaterialien ordnen Sie nach Themenfortschritt oder Schwierigkeitsgrad. Ber\u00fccksichtigen Sie den Lesefluss Ihres Publikums \u2013 was sollten sie zuerst sehen? Erstellen Sie ein gedankliches Inhaltsverzeichnis vor der Dateianordnung. Verwenden Sie beschreibende Dateinamen vor dem Zusammenf\u00fchren; \u201e01-Einleitung.pdf\u201c und \u201e02-Kapitel-Eins.pdf\u201c sortieren sich nat\u00fcrlich."
    },
    "s4": {
        "h": "Dateigr\u00f6\u00dfe beim Zusammenf\u00fchren verwalten",
        "p": "Die Dateigr\u00f6\u00dfe des zusammengef\u00fchrten PDFs entspricht der Summe aller Einzeldateien plus minimalem Overhead. Gro\u00dfe zusammengef\u00fchrte Dateien verursachen Probleme bei der E-Mail-\u00dcbertragung, langsame Downloads und schwierige Anzeige auf mobilen Ger\u00e4ten. Die Dateigr\u00f6\u00dfenverwaltung sollte vor dem Zusammenf\u00fchren beginnen.\n\nKomprimieren Sie einzelne PDFs vor dem Zusammenf\u00fchren, um die endg\u00fcltige Dateigr\u00f6\u00dfe zu reduzieren. Tuttilos PDF-Kompressor kann Dateigr\u00f6\u00dfen um 40-70% reduzieren. Entfernen Sie unn\u00f6tige Seiten aus Quelldokumenten vor dem Kombinieren \u2013 leere Seiten, Deckbl\u00e4tter und irrelevante Abschnitte erh\u00f6hen das Volumen. Wenn die zusammengef\u00fchrte Datei die Gr\u00f6\u00dfenbeschr\u00e4nkungen \u00fcberschreitet, erstellen Sie mehrere zusammengef\u00fchrte Dateien, organisiert nach Thema oder Datumsbereich. F\u00fcr sehr gro\u00dfe Sammlungen erstellen Sie ein Inhaltsverzeichnis-PDF mit Links zu separaten Kategoriedateien statt einer massiven Zusammenf\u00fchrung. W\u00e4gen Sie Vollst\u00e4ndigkeit gegen Nutzbarkeit ab \u2013 ein zusammengef\u00fchrtes PDF mit 200 Seiten mag technisch m\u00f6glich, aber praktisch unhandlich sein."
    },
    "s5": {
        "h": "Fortgeschrittene Zusammenf\u00fchrungstechniken",
        "p": "\u00dcber einfaches Dateikombinieren hinaus schaffen fortgeschrittene Zusammenf\u00fchrungstechniken anspruchsvollere Ergebnisse. Selektive Seitenzusammenf\u00fchrung erm\u00f6glicht das Extrahieren bestimmter Seiten aus gr\u00f6\u00dferen PDFs und das Kombinieren nur dieser Seiten. Extrahieren Sie die Seiten 1-5 aus einem Dokument, die Seiten 10-15 aus einem anderen, und f\u00fchren Sie nur diese Auswahl zusammen.\n\nVerschachtelte Zusammenf\u00fchrung verbindet zwei Dokumente Seite f\u00fcr Seite \u2013 Seite 1 von Dokument A, Seite 1 von Dokument B, Seite 2 von A, Seite 2 von B und so weiter. Diese Technik eignet sich f\u00fcr Gegen\u00fcberstellungen oder zweisprachige Dokumente. Stapelzusammenf\u00fchrung verarbeitet mehrere Dokumentens\u00e4tze nach Regeln. Zum Beispiel automatisches Zusammenf\u00fchren aller PDFs in bestimmten Ordnern zu datierten Archivdateien. Wenn Sie mit ausgef\u00fcllten Formular-PDFs arbeiten, \u00fcberpr\u00fcfen Sie, dass das Zusammenf\u00fchren ausf\u00fcllbare Felder bewahrt, falls Sie weiterhin Bearbeitbarkeit ben\u00f6tigen. Manche Zusammenf\u00fchrungsoperationen wandeln Formulare in statischen Inhalt um."
    },
    "s6": {
        "h": "H\u00e4ufige Zusammenf\u00fchrungsprobleme und L\u00f6sungen",
        "p": "Wenn zusammengef\u00fchrte PDFs Seiten in falscher Reihenfolge anzeigen, ist das Problem bei der Upload-Reihenfolge aufgetreten. Die meisten Tools bewahren die Upload-Reihenfolge, laden Sie also Dateien in Ihrer gew\u00fcnschten Reihenfolge hoch oder verwenden Sie Drag-and-Drop-Neuanordnung vor dem Zusammenf\u00fchren. \u00dcberpr\u00fcfen Sie die Dateinamen-Sortierung bei automatischer Anordnung.\n\nWenn zusammengef\u00fchrte Dateien besch\u00e4digt oder unlesbar erscheinen, k\u00f6nnten eine oder mehrere Quell-PDFs besch\u00e4digt sein. Testen Sie jede Quelldatei einzeln vor dem Zusammenf\u00fchren, um problematische Dateien zu identifizieren. Wenn das zusammengef\u00fchrte PDF Lesezeichen, Anmerkungen oder Formularfelder verliert, bewahrt das Zusammenf\u00fchrungstool diese Elemente m\u00f6glicherweise nicht. Tuttilos Zusammenf\u00fchrungstool bewahrt Standard-PDF-Funktionen, aber hochkomplexe interaktive PDFs k\u00f6nnen einige Funktionalit\u00e4t verlieren. Verwenden Sie in diesen F\u00e4llen professionelle PDF-Software. Wenn zusammengef\u00fchrte Dateien wegen ihrer Gr\u00f6\u00dfe nicht in bestimmte Systeme hochgeladen werden k\u00f6nnen, komprimieren Sie das zusammengef\u00fchrte PDF oder teilen Sie es in kleinere Abschnitte. Wenn passwortgesch\u00fctzte PDFs sich nicht zusammenf\u00fchren lassen, entfernen Sie die Passw\u00f6rter vor dem Zusammenf\u00fchren \u2013 die meisten Tools k\u00f6nnen verschl\u00fcsselte Dateien nicht verarbeiten."
    }
}

# 8. how-to-resize-images
de["how-to-resize-images"] = {
    "s1": {
        "h": "Warum Bildgr\u00f6\u00dfen\u00e4nderung wichtig ist",
        "p": "Die Gr\u00f6\u00dfen\u00e4nderung von Bildern ist entscheidend f\u00fcr moderne Web-Performance und Nutzererfahrung. Gro\u00dfe, nicht optimierte Bilder k\u00f6nnen Ihre Website erheblich verlangsamen, was zu h\u00f6heren Absprungraten und schlechteren SEO-Rankings f\u00fchrt. Suchmaschinen wie Google priorisieren schnell ladende Seiten in ihren Rankings.\n\n\u00dcber die Performance hinaus stellt die richtige Bildgr\u00f6\u00dfe sicher, dass Ihre Inhalte auf verschiedenen Ger\u00e4ten und Plattformen korrekt angezeigt werden. Social-Media-Plattformen haben spezifische Abmessungsanforderungen, und Bilder, die diese Spezifikationen nicht erf\u00fcllen, werden m\u00f6glicherweise beschnitten oder verzerrt dargestellt. Die angemessene Gr\u00f6\u00dfen\u00e4nderung von Bildern spart Bandbreitenkosten und verbessert die mobile Nutzererfahrung, bei der der Datenverbrauch ein kritisches Thema ist."
    },
    "s2": {
        "h": "G\u00e4ngige Bildabmessungen f\u00fcr verschiedene Plattformen",
        "p": "Jede Plattform hat optimale Bildabmessungen, die sicherstellen, dass Ihre Inhalte professionell wirken. F\u00fcr Social Media empfiehlt Facebook 1200\u00d7630 Pixel f\u00fcr geteilte Links, w\u00e4hrend Instagram-Beitr\u00e4ge am besten bei 1080\u00d71080 Pixel im Quadratformat oder 1080\u00d71350 im Hochformat funktionieren. Twitter-Headerbilder sollten 1500\u00d7500 Pixel gro\u00df sein.\n\nF\u00fcr Websites liegen Heldenbilder typischerweise bei 1920\u00d71080 Pixel f\u00fcr Header in voller Breite, w\u00e4hrend Blog-Beitragsbilder gut bei 1200\u00d7630 Pixel funktionieren. Produktbilder f\u00fcr E-Commerce-Seiten verwenden oft 1000\u00d71000 Pixel, um die Zoom-Funktion zu erm\u00f6glichen. Vorschaubilder k\u00f6nnen mit 150\u00d7150 bis 300\u00d7300 Pixel so klein sein, dass Sch\u00e4rfe und Dateigr\u00f6\u00dfe im Gleichgewicht bleiben."
    },
    "s3": {
        "h": "Qualit\u00e4t und Dateigr\u00f6\u00dfe ausbalancieren",
        "p": "Den optimalen Kompromiss zwischen Bildqualit\u00e4t und Dateigr\u00f6\u00dfe zu finden, ist f\u00fcr die Web-Performance unerl\u00e4sslich. F\u00fcr JPEG-Bilder liefert eine Qualit\u00e4tseinstellung zwischen 70-85% typischerweise hervorragende visuelle Ergebnisse bei deutlich reduzierter Dateigr\u00f6\u00dfe. Unter 70% k\u00f6nnen sichtbare Komprimierungsartefakte auftreten, besonders bei detailreichen Bildern.\n\nDie Zieldateigr\u00f6\u00dfe h\u00e4ngt von der Verwendung ab: Heldenbilder sollten unter 200KB bleiben, w\u00e4hrend kleinere Inhaltsbilder unter 100KB anstreben sollten. Verwenden Sie Tools wie Tuttilos Bildkompressor, um verschiedene Qualit\u00e4tseinstellungen zu testen und Ergebnisse zu vergleichen. Bedenken Sie, dass moderne Formate wie WebP die gleiche Qualit\u00e4t bei 25-35% kleineren Dateigr\u00f6\u00dfen als JPEG erreichen k\u00f6nnen, was sie zu ausgezeichneten Optionen f\u00fcr die Web-Nutzung macht, wenn die Browser-Unterst\u00fctzung es zul\u00e4sst."
    },
    "s4": {
        "h": "Schritt-f\u00fcr-Schritt-Bildgr\u00f6\u00dfen\u00e4nderung",
        "p": "Beginnen Sie damit, Ihre Zielabmessungen basierend auf dem Verwendungszweck des Bildes festzulegen. \u00d6ffnen Sie Ihr Bild in einem Gr\u00f6\u00dfen\u00e4nderungstool wie Tuttilos Bildresizer, das direkt in Ihrem Browser arbeitet, ohne auf Server hochzuladen. Geben Sie Ihre gew\u00fcnschte Breite und H\u00f6he ein und stellen Sie sicher, dass Sie das Seitenverh\u00e4ltnis beibehalten, es sei denn, Sie ben\u00f6tigen gezielt einen anderen Ausschnitt.\n\nW\u00e4hlen Sie Ihr Ausgabeformat basierend auf dem Bildinhalt: JPEG f\u00fcr Fotografien, PNG f\u00fcr Grafiken mit Transparenz oder WebP f\u00fcr moderne Browser. Passen Sie den Qualit\u00e4tsregler an, um die optimale Balance zwischen visueller Wiedergabetreue und Dateigr\u00f6\u00dfe zu finden. Sehen Sie sich das Ergebnis in der Vorschau an, bevor Sie es herunterladen. F\u00fcr Stapeloperationen sollten Sie Tools in Betracht ziehen, die mehrere Bilder gleichzeitig mit denselben Einstellungen verarbeiten k\u00f6nnen."
    },
    "s5": {
        "h": "Seitenverh\u00e4ltnis beibehalten vs. Zuschneiden",
        "p": "Die Beibehaltung des Seitenverh\u00e4ltnisses stellt sicher, dass Ihre Bilder nicht gestreckt oder verzerrt erscheinen. Wenn Sie das Seitenverh\u00e4ltnis beibehalten, geben Sie entweder Breite oder H\u00f6he an, und die andere Dimension wird automatisch proportional angepasst. Dieser Ansatz funktioniert am besten, wenn Sie Flexibilit\u00e4t bei den endg\u00fcltigen Abmessungen haben.\n\nAllerdings erfordern manche Anwendungsf\u00e4lle unabh\u00e4ngig vom urspr\u00fcnglichen Seitenverh\u00e4ltnis spezifische Abmessungen. Social-Media-Vorschaubilder brauchen oft exakte Abmessungen wie 1200\u00d7630 Pixel. In diesen F\u00e4llen m\u00fcssen Sie das Bild zuschneiden, was bedeutet, dass Sie ausw\u00e4hlen, welcher Teil des Originalbildes beibehalten wird. Verwenden Sie die Drittelregel und konzentrieren Sie sich beim Zuschneiden auf die wichtigsten Elemente. Intelligente Zuschneidewerkzeuge k\u00f6nnen Gesichter und wichtige Bereiche automatisch erkennen, aber manuelle Anpassung liefert bei kritischen Bildern oft bessere Ergebnisse."
    },
    "s6": {
        "h": "Best Practices und h\u00e4ufige Fehler",
        "p": "Arbeiten Sie wann immer m\u00f6glich mit hochaufl\u00f6senden Quellbildern, da Sie keine Details hinzuf\u00fcgen k\u00f6nnen, die urspr\u00fcnglich nicht vorhanden waren. Skalieren Sie Bilder nie deutlich hoch, da dies unscharfe, verpixelte Ergebnisse erzeugt. Verwenden Sie stattdessen die gr\u00f6\u00dfte verf\u00fcgbare Quelle und verkleinern Sie auf Ihre Zielabmessungen.\n\nVermeiden Sie die mehrfache Gr\u00f6\u00dfen\u00e4nderung von Bildern, da jeder Vorgang die Qualit\u00e4t verschlechtern kann. Speichern Sie Ihre Originaldateien und erstellen Sie neue Versionen f\u00fcr verschiedene Verwendungszwecke. F\u00fcr die Web-Nutzung sollten Sie die Erstellung mehrerer Gr\u00f6\u00dfen f\u00fcr responsive Bilder in Betracht ziehen, damit Browser die geeignetste Version basierend auf der Bildschirmgr\u00f6\u00dfe ausw\u00e4hlen k\u00f6nnen. Verwenden Sie beschreibende Dateinamen mit Abmessungen f\u00fcr eine einfache Organisation. Testen Sie Ihre verkleinerten Bilder auf tats\u00e4chlichen Ger\u00e4ten, um die korrekte Anzeige sicherzustellen \u2013 besonders bei kritischen Marketingmaterialien oder Produktfotos, die direkt die Konversionsraten beeinflussen."
    }
}

with open('/tmp/de_blog_part2.json', 'w', encoding='utf-8') as f:
    json.dump(de, f, ensure_ascii=False)
print(f"Part 2: {len(de)} articles total")
