#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json

with open('/tmp/de_blog_part2.json', 'r', encoding='utf-8') as f:
    de = json.load(f)

# 9. jpeg-vs-png-vs-webp
de["jpeg-vs-png-vs-webp"] = {
    "s1": {
        "h": "Grundlagen der Bildformate verstehen",
        "p": "Bildformate bestimmen, wie visuelle Daten gespeichert und komprimiert werden, und beeinflussen direkt Dateigr\u00f6\u00dfe, Qualit\u00e4t und Kompatibilit\u00e4t. JPEG (Joint Photographic Experts Group) ist seit 1992 der Webstandard, PNG (Portable Network Graphics) entstand 1996 als patentfreie Alternative zu GIF, und WebP ist Googles modernes Format, eingef\u00fchrt 2010.\n\nJedes Format dient unterschiedlichen Zwecken und gl\u00e4nzt in bestimmten Szenarien. Die Wahl zwischen ihnen beeinflusst Seitenladezeiten, Speicherkosten und Nutzererfahrung. Das Verst\u00e4ndnis ihrer technischen Unterschiede hilft Ihnen, fundierte Entscheidungen zu treffen, die Qualit\u00e4t, Performance und Kompatibilit\u00e4t ausbalancieren. Da \u00fcber 50% des Webtraffics von mobilen Ger\u00e4ten stammt, kann die Wahl des richtigen Formats den Datenverbrauch erheblich reduzieren und die Ladegeschwindigkeit verbessern."
    },
    "s2": {
        "h": "JPEG: Der Standard f\u00fcr Fotografie",
        "p": "JPEG verwendet verlustbehaftete Komprimierung, was bedeutet, dass einige Bilddaten dauerhaft verworfen werden, um kleinere Dateigr\u00f6\u00dfen zu erreichen. Dies macht es ideal f\u00fcr Fotografien und komplexe Bilder mit vielen Farben und Verl\u00e4ufen, bei denen das menschliche Auge geringf\u00fcgige Qualit\u00e4tseinbu\u00dfen nicht bemerkt. JPEG kann Millionen von Farben darstellen und eignet sich hervorragend f\u00fcr die Komprimierung nat\u00fcrlicher Szenen.\n\nJPEG unterst\u00fctzt jedoch keine Transparenz und verliert bei jedem Speichern an Qualit\u00e4t. Es eignet sich nicht f\u00fcr Bilder mit scharfen Kanten, Text oder einfachen Grafiken, da Komprimierungsartefakte in diesen F\u00e4llen sichtbar werden. Dateigr\u00f6\u00dfen f\u00fcr JPEG-Bilder liegen f\u00fcr Webnutzung typischerweise zwischen 50KB und 500KB, abh\u00e4ngig von Abmessungen und Qualit\u00e4tseinstellungen. Das Format wird von allen Browsern und Ger\u00e4ten universell unterst\u00fctzt und ist damit die sicherste Wahl f\u00fcr breite Kompatibilit\u00e4t."
    },
    "s3": {
        "h": "PNG: Transparenz und verlustfreie Qualit\u00e4t",
        "p": "PNG verwendet verlustfreie Komprimierung und bewahrt jedes Pixel des Originalbilds perfekt. Dies macht es ideal f\u00fcr Screenshots, Logos, Icons und Grafiken mit Text oder scharfen Kanten. PNG unterst\u00fctzt Transparenz \u00fcber einen Alpha-Kanal und erm\u00f6glicht glatte Kanten und \u00dcberlagerungen, die JPEG nicht bieten kann.\n\nDer Kompromiss sind deutlich gr\u00f6\u00dfere Dateigr\u00f6\u00dfen im Vergleich zu JPEG f\u00fcr fotografische Inhalte. PNG gibt es in zwei Hauptvarianten: PNG-8 (256 Farben, kleinere Dateien) und PNG-24 (Millionen Farben, gr\u00f6\u00dfere Dateien). F\u00fcr die Webnutzung liegen PNG-Dateien oft zwischen 100KB und \u00fcber 1MB f\u00fcr detaillierte Bilder. Verwenden Sie PNG, wenn Sie Transparenz, perfekte Qualit\u00e4tserhaltung ben\u00f6tigen oder mit Grafiken statt Fotografien arbeiten. Tools wie Tuttilos Bildkonverter erleichtern das Wechseln zwischen Formaten je nach Bedarf."
    },
    "s4": {
        "h": "WebP: Das moderne Web-Format",
        "p": "WebP unterst\u00fctzt sowohl verlustbehaftete als auch verlustfreie Komprimierung und vereint die besten Aspekte von JPEG und PNG. Google berichtet, dass verlustbehaftete WebP-Bilder 25-35% kleiner als JPEG bei gleicher Qualit\u00e4t sind, w\u00e4hrend verlustfreie WebP-Bilder 26% kleiner als PNG sind. WebP unterst\u00fctzt auch Transparenz und Animation.\n\nDie Browser-Unterst\u00fctzung hat sich dramatisch verbessert, wobei \u00fcber 95% der Nutzer weltweit WebP-kompatible Browser verwenden (Stand 2024). Die Haupteinschr\u00e4nkung sind \u00e4ltere Browser wie Internet Explorer, der nie WebP-Unterst\u00fctzung hinzugef\u00fcgt hat. F\u00fcr kritische Bilder implementieren Sie Fallbacks mit dem HTML-Picture-Element. WebP gl\u00e4nzt in allen Szenarien: Fotografien, Grafiken, Bilder mit Transparenz und sogar animierte Bilder. Die Vielseitigkeit und \u00fcberlegene Komprimierung des Formats machen es zur optimalen Wahl f\u00fcr moderne Webprojekte, wenn R\u00fcckw\u00e4rtskompatibilit\u00e4t nicht erforderlich ist."
    },
    "s5": {
        "h": "Performance-Auswirkungen und Dateigr\u00f6\u00dfenvergleich",
        "p": "Die Dateigr\u00f6\u00dfe beeinflusst die Seitenladezeit direkt, besonders bei mobilen Verbindungen. F\u00fcr ein typisches 1200\u00d7800-Foto in guter Qualit\u00e4t k\u00f6nnte JPEG 150KB betragen, PNG-24 k\u00f6nnte 800KB sein, und WebP w\u00e4re etwa 100KB. Diese 50KB Unterschied zwischen JPEG und WebP mag gering erscheinen, summiert sich aber bei Dutzenden von Bildern auf einer Seite erheblich.\n\nF\u00fcr Grafiken mit Transparenz \u00e4ndert sich der Vergleich dramatisch. Ein 500\u00d7500-Logo k\u00f6nnte 20KB als WebP, 60KB als PNG-8 oder 150KB als PNG-24 sein. JPEG ist aufgrund fehlender Transparenzunterst\u00fctzung keine Option. Die Verwendung von WebP f\u00fcr eine Website mit 50 Bildern k\u00f6nnte das Gesamtgewicht der Seite um 1-2MB reduzieren und die Ladezeit bei langsameren Verbindungen um mehrere Sekunden verk\u00fcrzen. Diese Verbesserung \u00fcbersetzt sich direkt in bessere Nutzererfahrung, niedrigere Absprungraten und verbesserte SEO-Rankings."
    },
    "s6": {
        "h": "Wann welches Format verwenden",
        "p": "Verwenden Sie JPEG f\u00fcr Fotografien, Produktbilder und alle komplexen Bilder ohne Transparenz, wenn Sie maximale Browser-Kompatibilit\u00e4t ben\u00f6tigen. Es bleibt die beste Wahl f\u00fcr E-Mail-Marketing und Situationen, in denen Sie die Anzeigenumgebung nicht kontrollieren k\u00f6nnen.\n\nW\u00e4hlen Sie PNG f\u00fcr Logos, Icons, Screenshots, Grafiken mit Text, Diagramme und alle Bilder, die Transparenz oder perfekte Qualit\u00e4tserhaltung erfordern. PNG ist unerl\u00e4sslich f\u00fcr Bilder, die mehrfach bearbeitet werden, da es im Gegensatz zu JPEG bei wiederholtem Speichern nicht degradiert.\n\nW\u00e4hlen Sie WebP als Standardformat f\u00fcr moderne Webprojekte. Verwenden Sie es f\u00fcr Fotografien (verlustbehafteter Modus), Grafiken mit Transparenz (verlustfreier Modus) und Animationen (als GIF-Ersatz). Implementieren Sie geeignete Fallbacks f\u00fcr \u00e4ltere Browser mittels Picture-Element oder serverseitiger Erkennung. F\u00fcr optimale Ergebnisse nutzen Sie Tuttilos Bildkonverter, um mehrere Formatversionen zu erstellen und Dateigr\u00f6\u00dfen zu vergleichen und die kleinste Datei zu w\u00e4hlen, die Ihre Qualit\u00e4tsanforderungen erf\u00fcllt."
    }
}

# 10. pdf-vs-word
de["pdf-vs-word"] = {
    "s1": {
        "h": "Wesentliche Unterschiede zwischen PDF und Word",
        "p": "PDF (Portable Document Format) und Word-Dokumente dienen grunds\u00e4tzlich unterschiedlichen Zwecken. Word-Dateien sind f\u00fcr Erstellung und Bearbeitung konzipiert, mit dynamischer Formatierung, die sich je nach Softwareversion, installierten Schriftarten und Systemeinstellungen \u00e4ndern kann. PDFs sind f\u00fcr Distribution und Anzeige konzipiert und bewahren die exakte Formatierung \u00fcber alle Ger\u00e4te und Plattformen hinweg.\n\nWord-Dokumente haben die Erweiterung .docx und erfordern Microsoft Word oder kompatible Software zum vollst\u00e4ndigen \u00d6ffnen und Bearbeiten. PDFs verwenden die Erweiterung .pdf und k\u00f6nnen auf praktisch jedem Ger\u00e4t mit kostenloser Software angezeigt werden. Der Kernunterschied liegt in der Absicht: Word ist ein Arbeitsformat f\u00fcr die Dokumententwicklung, w\u00e4hrend PDF ein Endformat f\u00fcr das Teilen von Dokumenten ist. Das Verst\u00e4ndnis dieser Unterscheidung hilft Ihnen, das richtige Format f\u00fcr jede Phase Ihres Dokumenten-Workflows zu w\u00e4hlen."
    },
    "s2": {
        "h": "Vorteile von PDF-Dokumenten",
        "p": "PDFs bewahren perfekte visuelle Konsistenz \u00fcber alle Ger\u00e4te, Betriebssysteme und Bildschirmgr\u00f6\u00dfen hinweg. Ein auf Windows erstelltes PDF sieht auf Mac, Linux oder mobilen Ger\u00e4ten identisch aus, unabh\u00e4ngig davon, ob der Betrachter die verwendeten Schriftarten installiert hat. Dies macht PDF ideal f\u00fcr offizielle Dokumente, Vertr\u00e4ge, Berichte und jedes Material, bei dem die exakte Pr\u00e4sentation wichtig ist.\n\nPDFs sind sicherer als Word-Dokumente. Sie k\u00f6nnen PDFs mit Passwort sch\u00fctzen, Drucken oder Bearbeiten einschr\u00e4nken und digitale Signaturen f\u00fcr Authentizit\u00e4t hinzuf\u00fcgen. PDFs sind auch sicherer zum Teilen mit externen Parteien, da sie keine versteckten Makros oder ausf\u00fchrbaren Code enthalten, die Sicherheitsrisiken darstellen k\u00f6nnten. Dateigr\u00f6\u00dfen sind oft kleiner als \u00e4quivalente Word-Dokumente, besonders bei Dokumenten mit vielen Bildern. Zus\u00e4tzlich sind PDFs der Standard f\u00fcr Archivierung und Druck und gew\u00e4hrleisten langfristige Zug\u00e4nglichkeit und professionelle Ausgabe."
    },
    "s3": {
        "h": "Vorteile von Word-Dokumenten",
        "p": "Word-Dokumente eignen sich hervorragend f\u00fcr kollaborative Bearbeitung und iterative Entwicklung. Mehrere Nutzer k\u00f6nnen \u00c4nderungen nachverfolgen, Kommentare hinzuf\u00fcgen und Bearbeitungen vorschlagen, ohne den urspr\u00fcnglichen Inhalt zu ver\u00e4ndern. Versionskontrollfunktionen helfen Teams, die Dokumententwicklung \u00fcber die Zeit zu verwalten und eine klare Historie der \u00c4nderungen beizubehalten.\n\nWord bietet \u00fcberlegene Bearbeitungsflexibilit\u00e4t mit fortgeschrittenen Formatierungswerkzeugen, Formatvorlagen, Vorlagen und Layoutoptionen. Sie k\u00f6nnen Inhalte einfach neu ordnen, Formatierung global mit Formatvorlagen aktualisieren und mit anderen Microsoft-Office-Tools wie Excel-Diagrammen oder Daten integrieren. Words Rechtschreib- und Grammatikpr\u00fcfung sowie Schreibhilfen helfen bei der Erstellung ausgefeilter Inhalte. F\u00fcr Dokumente, die mehrere \u00dcberarbeitungen durchlaufen oder h\u00e4ufige Aktualisierungen ben\u00f6tigen, ist Word die klare Wahl. Das Format eignet sich auch besser f\u00fcr Dokumente, bei denen der Inhalt wichtiger ist als das pr\u00e4zise visuelle Layout, wie Entw\u00fcrfe, interne Mitteilungen oder Arbeitsdokumente."
    },
    "s4": {
        "h": "Wann PDF verwenden",
        "p": "Verwenden Sie PDF f\u00fcr jedes Dokument, das Sie extern verteilen und bei dem Sie genau kontrollieren m\u00f6chten, wie es erscheint. Lebensl\u00e4ufe, Portfolios, Rechnungen, Vertr\u00e4ge und offizielle Formulare sollten immer PDFs sein, um zu verhindern, dass Empf\u00e4nger unbefugte \u00c4nderungen vornehmen. PDFs sind unerl\u00e4sslich f\u00fcr druckfertige Dokumente, damit die Druckerei genau das sieht, was Sie gestaltet haben.\n\nW\u00e4hlen Sie PDF f\u00fcr Dokumente, die Unterschriften erfordern, ob digital oder ausgedruckt. Rechtsvereinbarungen, HR-Dokumente und Compliance-Formulare profitieren von den Sicherheitsfunktionen und der Manipulationssicherheit von PDF. Verwenden Sie PDF f\u00fcr die Archivierung endg\u00fcltiger Versionen wichtiger Dokumente, da das Format f\u00fcr langfristige Aufbewahrung konzipiert ist und ISO-Standardisierung besitzt. E-Books, Whitepaper und Marketingmaterialien sollten PDFs sein, um Markenkonsistenz und professionelle Pr\u00e4sentation zu wahren. Tuttilos PDF-Tools erleichtern das Erstellen, Bearbeiten und Konvertieren von PDFs ohne teure Softwareabonnements."
    },
    "s5": {
        "h": "Wann Word verwenden",
        "p": "Verwenden Sie Word f\u00fcr jedes Dokument, das sich noch in Entwicklung befindet oder h\u00e4ufige Bearbeitungen erfordert. Besprechungsnotizen, Berichtsentw\u00fcrfe, Projektpl\u00e4ne und interne Dokumentation profitieren von Words Bearbeitungs- und Zusammenarbeitsfunktionen. W\u00e4hlen Sie Word, wenn Sie mit Teammitgliedern zusammenarbeiten, die Inhalte beisteuern, \u00c4nderungen vorschlagen oder Entw\u00fcrfe \u00fcberpr\u00fcfen m\u00fcssen.\n\nWord ist ideal f\u00fcr vorlagenbasierte Dokumente, bei denen sich der Inhalt \u00e4ndert, die Struktur aber konsistent bleibt. Briefe, Angebote und Standardarbeitsanweisungen beginnen oft als Word-Vorlagen. Verwenden Sie Word f\u00fcr Dokumente, bei denen pr\u00e4zises Layout nicht kritisch ist, wie reine Textberichte, akademische Arbeiten oder Forschungsnotizen. Words Barrierefreiheitsfunktionen und Screenreader-Kompatibilit\u00e4t machen es besser f\u00fcr Dokumente, die prim\u00e4r als Text und nicht als visuelle Layouts konsumiert werden. Wenn Ihr Dokument letztendlich ein PDF wird, gibt Ihnen der Start in Word Bearbeitungsflexibilit\u00e4t w\u00e4hrend der Entwicklung."
    },
    "s6": {
        "h": "Zwischen PDF und Word konvertieren",
        "p": "Die Konvertierung von Word zu PDF ist unkompliziert und bewahrt die Formatierung gut. Moderne Word-Versionen enthalten einen integrierten PDF-Export, oder Sie k\u00f6nnen kostenlose Online-Konverter wie die auf Tuttilo verf\u00fcgbaren verwenden. Diese Konvertierung ist f\u00fcr Standarddokumente in der Regel verlustfrei und beh\u00e4lt Layout, Schriftarten und Bilder genau bei.\n\nDie Konvertierung von PDF zu Word ist komplexer und die Ergebnisse variieren je nach Ursprung des PDFs. Aus Word erstellte PDFs konvertieren relativ sauber, w\u00e4hrend gescannte Dokumente oder komplexe Layouts unvollkommene Ergebnisse liefern k\u00f6nnen. OCR (Optical Character Recognition) ist f\u00fcr gescannte PDFs erforderlich, und selbst dann muss die Formatierung oft manuell nachbearbeitet werden. Tabellen, mehrspaltiges Layout und eingebettete Bilder k\u00f6nnen Konvertierungsprobleme verursachen.\n\nF\u00fcr beste Ergebnisse bewahren Sie die Word-Quelldateien, statt sich auf PDF-zu-Word-Konvertierung zu verlassen. Wenn Sie konvertieren m\u00fcssen, verwenden Sie spezialisierte Konvertierungstools und rechnen Sie damit, die Formatierung \u00fcberpr\u00fcfen und korrigieren zu m\u00fcssen. F\u00fcr Dokumente, die beide Formate ben\u00f6tigen, erstellen Sie das endg\u00fcltige PDF aus Ihrer Word-Quelle, statt hin und her zu konvertieren, da jede Konvertierung Fehler oder Formatierungsverschlechterungen einf\u00fchren kann."
    }
}

# 11. md5-vs-sha256
de["md5-vs-sha256"] = {
    "s1": {
        "h": "Was sind Hash-Funktionen",
        "p": "Hash-Funktionen sind mathematische Algorithmen, die beliebige Eingabedaten in eine Zeichenkette fester L\u00e4nge umwandeln, den sogenannten Hash oder Digest. Diese Funktionen sind deterministisch \u2013 dieselbe Eingabe erzeugt immer dieselbe Ausgabe. Hash-Funktionen sind Einwegoperationen: Man kann den Hash nicht umkehren, um die Originaldaten abzurufen.\n\nKryptografische Hash-Funktionen haben drei kritische Eigenschaften: Sie sind schnell zu berechnen, es ist praktisch unm\u00f6glich, zwei verschiedene Eingaben zu finden, die denselben Hash erzeugen (Kollisionsresistenz), und selbst kleinste Eingabe\u00e4nderungen erzeugen komplett andere Hashes (Lawineneffekt). Diese Eigenschaften machen Hash-Funktionen unerl\u00e4sslich f\u00fcr Passwortspeicherung, Datenintegrit\u00e4tspr\u00fcfung, digitale Signaturen und Blockchain-Technologie. MD5 und SHA-256 sind zwei der bekanntesten Hash-Funktionen, unterscheiden sich aber erheblich in Sicherheit und geeigneten Anwendungsf\u00e4llen."
    },
    "s2": {
        "h": "MD5: Der veraltete Standard",
        "p": "MD5 (Message Digest Algorithm 5) wurde 1991 von Ronald Rivest entwickelt und erzeugt einen 128-Bit-Hash (16 Byte), der typischerweise als 32-stellige Hexadezimalzeichenkette dargestellt wird. Es wurde in den 1990er und fr\u00fchen 2000er Jahren aufgrund seiner Geschwindigkeit und Einfachheit weit verbreitet f\u00fcr Dateiintegrit\u00e4tspr\u00fcfung und Passwort-Hashing eingesetzt.\n\nAllerdings wurden ab 1996 ernsthafte kryptografische Schw\u00e4chen in MD5 entdeckt, und 2004 wurden praktische Kollisionsangriffe demonstriert. Forscher zeigten, dass sie zwei verschiedene Dateien mit identischen MD5-Hashes in weniger als einer Stunde auf Standardcomputern erstellen konnten. Bis 2008 hatten Angreifer SSL-Zertifikate mithilfe von MD5-Kollisionen erfolgreich gef\u00e4lscht. Diese Schwachstellen machen MD5 f\u00fcr alle sicherheitsrelevanten Anwendungen ungeeignet. Dennoch bleibt MD5 n\u00fctzlich f\u00fcr nicht-sicherheitsrelevante Zwecke wie Pr\u00fcfsummen zur Erkennung versehentlicher Dateikorrumpierung, bei denen absichtliche Manipulation kein Thema ist."
    },
    "s3": {
        "h": "SHA-256: Moderner Sicherheitsstandard",
        "p": "SHA-256 geh\u00f6rt zur SHA-2-Familie von Hash-Funktionen, die von der NSA entwickelt und 2001 ver\u00f6ffentlicht wurden. Es erzeugt einen 256-Bit-Hash (32 Byte), dargestellt als 64-stellige Hexadezimalzeichenkette. SHA-256 ist deutlich sicherer als MD5, ohne dass trotz umfangreicher Kryptoanalyse \u00fcber zwei Jahrzehnte praktische Kollisionsangriffe entdeckt wurden.\n\nDie l\u00e4ngere Hashl\u00e4nge bietet exponentiell mehr m\u00f6gliche Ausgaben \u2013 2^256 m\u00f6gliche Hashes im Vergleich zu MD5s 2^128. Dies macht Brute-Force-Angriffe mit aktueller oder absehbarer Technologie rechnerisch undurchf\u00fchrbar. SHA-256 ist der aktuelle Standard f\u00fcr sicherheitskritische Anwendungen, einschlie\u00dflich SSL/TLS-Zertifikate, Blockchain-Technologie (Bitcoin verwendet SHA-256), Code-Signierung und sicheres Passwort-Hashing. Obwohl langsamer als MD5, berechnen moderne Prozessoren SHA-256-Hashes f\u00fcr typische Daten in Millisekunden, sodass der Sicherheitsvorteil den minimalen Performancekosten mehr als wert ist."
    },
    "s4": {
        "h": "Sicherheitsunterschiede und Schwachstellen",
        "p": "Der grundlegende Sicherheitsunterschied liegt in der Kollisionsresistenz. MD5s 128-Bit-Ausgabe bedeutet, dass das Finden einer Kollision aufgrund des Geburtstagsparadoxons etwa 2^64 Operationen erfordert \u2013 erreichbar mit moderner Rechenleistung. Angreifer haben praktische MD5-Kollisionen in Minuten demonstriert, mit denen sie b\u00f6sartige Dateien erstellen k\u00f6nnen, die bei MD5-Hash-\u00dcberpr\u00fcfung legitim erscheinen.\n\nSHA-256s 256-Bit-Ausgabe erfordert etwa 2^128 Operationen, um eine Kollision zu finden \u2013 eine Zahl so gro\u00df, dass sie die Rechenkapazit\u00e4t aller Computer auf der Erde \u00fcber Jahrtausende \u00fcbersteigt. Es existieren keine praktischen Kollisionsangriffe gegen SHA-256. MD5 ist auch anf\u00e4llig f\u00fcr Length-Extension-Angriffe und Preimage-Angriffe, die theoretisch demonstriert wurden. SHA-256 widersteht allen bekannten kryptografischen Angriffen. F\u00fcr Passwort-Hashing wird MD5s Geschwindigkeit zur Belastung, da Angreifer Milliarden von Passwort-Versuchen pro Sekunde testen k\u00f6nnen. SHA-256 ist besser, aber immer noch zu schnell \u2013 spezialisierte Passwort-Hashing-Funktionen wie bcrypt oder Argon2 werden empfohlen."
    },
    "s5": {
        "h": "Praktische Anwendungsf\u00e4lle f\u00fcr jeden",
        "p": "Verwenden Sie MD5 nur f\u00fcr nicht-sicherheitsrelevante Anwendungen, bei denen Sie versehentliche Korrumpierung erkennen m\u00fcssen, aber keine absichtliche Manipulation. Beispiele sind Pr\u00fcfsummen f\u00fcr heruntergeladene Dateien von vertrauensw\u00fcrdigen Quellen, Deduplizierungsidentifikatoren in Backup-Systemen oder Cache-Schl\u00fcssel in Webanwendungen. MD5s Geschwindigkeit macht es f\u00fcr diese Zwecke effizient, und seine Schw\u00e4chen spielen keine Rolle, wenn Sicherheit nicht erforderlich ist.\n\nVerwenden Sie SHA-256 f\u00fcr alle sicherheitsrelevanten Anwendungen. Digitale Signaturen, Zertifikatsverifizierung, Blockchain-Implementierungen und sichere Token-Generierung erfordern alle SHA-256 oder st\u00e4rker. Dateiintegrit\u00e4ts\u00fcberwachung in Sicherheitskontexten ben\u00f6tigt SHA-256, um zu verhindern, dass Angreifer modifizierte Dateien mit passenden Hashes erstellen. Git verwendet SHA-256 (als Ersatz f\u00fcr SHA-1) f\u00fcr Commit-Hashes, um die Repository-Integrit\u00e4t sicherzustellen. API-Authentifizierungstoken und Sitzungsidentifikatoren sollten SHA-256 verwenden. Tools wie Tuttilos Hash-Generator erleichtern das Erstellen von MD5- und SHA-256-Hashes zum Vergleich und f\u00fcr den geeigneten Einsatz."
    },
    "s6": {
        "h": "Migration und Best Practices",
        "p": "Wenn Sie MD5 derzeit f\u00fcr Sicherheitszwecke verwenden, migrieren Sie sofort zu SHA-256. F\u00fcr Passwort-Hashes wechseln Sie zu bcrypt, scrypt oder Argon2, die speziell f\u00fcr die Passwortspeicherung mit anpassbaren Rechenkosten entwickelt wurden. Aktualisieren Sie Dateiintegrit\u00e4tssysteme auf SHA-256 und behalten Sie MD5 nur vor\u00fcbergehend bei, wenn R\u00fcckw\u00e4rtskompatibilit\u00e4t mit Legacy-Systemen erforderlich ist.\n\nVerwenden Sie f\u00fcr neue Projekte standardm\u00e4\u00dfig SHA-256 f\u00fcr alle Hashing-Anforderungen, es sei denn, Sie haben bestimmte Gr\u00fcnde f\u00fcr Alternativen. SHA-3 (der neueste Standard) bietet \u00e4hnliche Sicherheit wie SHA-256 mit anderem internem Design und ist eine Alternative, falls jemals Schwachstellen in der SHA-2-Familie entdeckt werden. Verwenden Sie MD5 niemals f\u00fcr Passwort-Hashing, digitale Signaturen, Zertifikatserstellung oder kryptografische Schl\u00fcsselableitung.\n\nDokumentieren Sie, welche Hash-Funktion Sie verwenden und warum, besonders bei der Umstellung zwischen Algorithmen. Verwenden Sie beim Vergleich von Hashes Konstantzeit-Vergleichsfunktionen, um Timing-Angriffe zu verhindern. Denken Sie daran, dass Hashing allein keine Daten verschl\u00fcsselt \u2013 wenn Sie Daten vertraulich sch\u00fctzen m\u00fcssen, verwenden Sie Verschl\u00fcsselungsalgorithmen wie AES zus\u00e4tzlich zum Hashing f\u00fcr die Integrit\u00e4tspr\u00fcfung."
    }
}

# 12. rgb-vs-hex-vs-hsl
de["rgb-vs-hex-vs-hsl"] = {
    "s1": {
        "h": "Farbmodelle verstehen",
        "p": "Farbformate beschreiben, wie wir Farben in digitalem Design und Code definieren. RGB (Rot, Gr\u00fcn, Blau), HEX (Hexadezimal) und HSL (Farbton, S\u00e4ttigung, Helligkeit) beschreiben alle dieselben Farben, verwenden aber unterschiedliche mathematische Modelle. Das Verst\u00e4ndnis dieser Modelle hilft Ihnen, effizienter zu arbeiten und Farbentscheidungen klar zu kommunizieren.\n\nRGB ist ein additives Farbmodell, das darauf basiert, wie Bildschirme Licht durch Kombination von Rot, Gr\u00fcn und Blau erzeugen. HEX ist einfach eine andere Notation f\u00fcr RGB unter Verwendung hexadezimaler Zahlen. HSL ist ein zylindrisches Farbmodell, das Farben in Begriffen beschreibt, die f\u00fcr Menschen intuitiver sind. Alle drei werden in modernem CSS vollst\u00e4ndig unterst\u00fctzt und k\u00f6nnen dieselben 16,7 Millionen Farben darstellen (24-Bit-Farbtiefe). Die Wahl zwischen ihnen beeinflusst Code-Lesbarkeit, einfache Manipulation und Workflow-Effizienz."
    },
    "s2": {
        "h": "RGB: Das Bildschirm-Farbmodell",
        "p": "RGB dr\u00fcckt Farben mit drei Werten aus, die die Rot-, Gr\u00fcn- und Blaulichtintensit\u00e4t darstellen, jeweils von 0 bis 255. Reines Rot ist rgb(255, 0, 0), reines Blau ist rgb(0, 0, 255) und Wei\u00df ist rgb(255, 255, 255), wobei alle Kan\u00e4le maximal sind. Schwarz ist rgb(0, 0, 0) mit allen Kan\u00e4len aus.\n\nRGB-Werte entsprechen direkt der Funktionsweise von Bildschirmen, die Licht mischen, um Farben zu erzeugen. Dies macht RGB intuitiv, wenn man \u00fcber Bildschirmanzeigetechnologie nachdenkt. CSS unterst\u00fctzt rgb()- und rgba()-Funktionen, wobei das \u201ea\u201c einen Alpha-Kanal f\u00fcr Transparenz hinzuf\u00fcgt (0 bis 1). Zum Beispiel ist rgba(255, 0, 0, 0.5) halbtransparentes Rot. RGB ist f\u00fcr Programmierer, die mit numerischen Werten vertraut sind, leicht zu verstehen und funktioniert gut, wenn Sie einzelne Farbkan\u00e4le programmgesteuert manipulieren m\u00fcssen. Allerdings erfordert das Erstellen von Farbvariationen wie \u201eeine hellere Version dieses Blau\u201c Kopfrechnen oder Tools."
    },
    "s3": {
        "h": "HEX: Die Kurzschrift f\u00fcr Entwickler",
        "p": "HEX-Farbcodes stellen RGB-Werte in hexadezimaler Notation dar, mit Basis-16-Zahlen (0-9 und A-F). Eine HEX-Farbe beginnt mit # gefolgt von sechs Zeichen: zwei f\u00fcr Rot, zwei f\u00fcr Gr\u00fcn, zwei f\u00fcr Blau. #FF0000 ist reines Rot (FF=255 dezimal), #0000FF ist reines Blau, #FFFFFF ist Wei\u00df und #000000 ist Schwarz.\n\nHEX-Codes k\u00f6nnen auf drei Zeichen verk\u00fcrzt werden, wenn jeder Farbkanal doppelte Ziffern hat: #F00 entspricht #FF0000. Diese Kurzform ist \u00fcblich f\u00fcr Farben wie #FFF (Wei\u00df) oder #000 (Schwarz). HEX ist die kompakteste Farbnotation und war der traditionelle Standard in der Webentwicklung. Es l\u00e4sst sich leicht kopieren und einf\u00fcgen, und Tools wie Farbw\u00e4hler geben typischerweise HEX-Codes aus. HEX unterst\u00fctzt allerdings keine Transparenz in CSS (obwohl einige Designtools achtstellige HEX-Codes mit Alpha-Kanal verwenden). HEX-Werte sind schwerer zu lesen und mental anzupassen als RGB oder HSL, was sie weniger intuitiv f\u00fcr das Erstellen von Farbvariationen macht."
    },
    "s4": {
        "h": "HSL: Die Wahl f\u00fcr Designer",
        "p": "HSL beschreibt Farben mit Farbton, S\u00e4ttigung und Helligkeit. Der Farbton ist der Farbtyp (0-360 Grad auf einem Farbkreis: 0/360 ist Rot, 120 ist Gr\u00fcn, 240 ist Blau). Die S\u00e4ttigung ist die Farbintensit\u00e4t (0% ist Grau, 100% ist volle Farbe). Die Helligkeit ist die Leuchtkraft (0% ist Schwarz, 50% ist reine Farbe, 100% ist Wei\u00df).\n\nHSL entspricht der Art, wie Designer \u00fcber Farbe denken. Um eine Farbe heller zu machen, erh\u00f6hen Sie den Helligkeitswert. Um sie lebhafter zu machen, erh\u00f6hen Sie die S\u00e4ttigung. Um den Farbton zu verschieben, passen Sie den Farbtongrad an. Dies macht HSL unglaublich m\u00e4chtig f\u00fcr die Erstellung von Farbschemata und Variationen. Zum Beispiel ist hsl(240, 100%, 50%) reines Blau; hsl(240, 100%, 75%) ist ein helleres Blau; hsl(240, 50%, 50%) ist ein weniger ges\u00e4ttigtes Blau. CSS unterst\u00fctzt hsla() f\u00fcr Transparenz. HSL ist perfekt f\u00fcr das programmgesteuerte Generieren von Farbpaletten, das Erstellen von Hover-Effekten durch Helligkeitsanpassung und die Aufrechterhaltung konsistenter Farbbeziehungen \u00fcber ein Designsystem hinweg."
    },
    "s5": {
        "h": "Zwischen Farbformaten konvertieren",
        "p": "Das Konvertieren zwischen diesen Formaten ist mit Tools unkompliziert, aber konzeptionell n\u00fctzlich zu verstehen. HEX zu RGB ist einfach: Konvertieren Sie jedes Paar hexadezimaler Ziffern in Dezimal. #FF5733 wird rgb(255, 87, 51), wobei FF=255, 57=87, 33=51. RGB zu HEX kehrt diesen Prozess um und konvertiert Dezimal in Hexadezimal.\n\nRGB zu HSL ist komplexer und erfordert das Finden der maximalen und minimalen RGB-Werte, die Berechnung der Helligkeit, dann der S\u00e4ttigung und schlie\u00dflich des Farbtons basierend darauf, welcher Kanal dominant ist. HSL zu RGB erfordert je nach Farbtonbereich unterschiedliche Formeln. Statt diese Berechnungen manuell durchzuf\u00fchren, verwenden Sie Tools wie Tuttilos Farbkonverter, um sofort zwischen Formaten zu wechseln. Design-Tools wie Figma und Adobe XD zeigen alle drei Formate gleichzeitig an. Browser-Entwicklertools erm\u00f6glichen das Klicken auf Farbwerte, um zwischen RGB, HEX und HSL zu wechseln. Modernes CSS unterst\u00fctzt auch color-mix() und relative Farbsyntax f\u00fcr das Erstellen von Variationen ohne manuelle Konvertierung."
    },
    "s6": {
        "h": "Wann welches Format verwenden",
        "p": "Verwenden Sie HEX, wenn Sie kompakte, portable Farbcodes w\u00fcnschen, die sich leicht kopieren und einf\u00fcgen lassen. HEX ist Standard bei Design-\u00dcbergaben und Styleguides. Es eignet sich perfekt f\u00fcr statische Farben, die nicht programmgesteuert manipuliert werden. Bleiben Sie bei HEX f\u00fcr Markenfarben, exakte Farbspezifikationen und bei der Zusammenarbeit mit Designern, die dieses Format bevorzugen.\n\nVerwenden Sie RGB bei der Arbeit mit JavaScript oder wenn Transparenz ben\u00f6tigt wird. Die rgba()-Funktion wird historisch breiter unterst\u00fctzt als HEX mit Alpha. RGB ist auch klarer bei der programmgesteuerten Farbmanipulation, da Sie Kanalwerte direkt anpassen k\u00f6nnen. Verwenden Sie RGB f\u00fcr Berechnungen, Bildverarbeitung oder bei der Anbindung an Grafikbibliotheken.\n\nVerwenden Sie HSL beim Erstellen von Farbsystemen, Themes oder dynamischen Farbvariationen. HSL macht es trivial, hellere/dunklere Versionen zu erzeugen, Komplement\u00e4rfarben zu erstellen oder die S\u00e4ttigung \u00fcber eine Palette anzupassen. Verwenden Sie HSL f\u00fcr CSS-Variablen in Designsystemen, wo Sie Basisfarbton und S\u00e4ttigung definieren und die Helligkeit f\u00fcr verschiedene UI-Zust\u00e4nde variieren k\u00f6nnen. HSL ist ideal f\u00fcr barrierefreie Farbsysteme, da Sie mathematisch ausreichenden Helligkeitskontrast sicherstellen k\u00f6nnen. F\u00fcr moderne Webentwicklung mit dynamischem Theming oder Farbmanipulation ist HSL oft die wartbarste Wahl."
    }
}

with open('/tmp/de_blog_part3.json', 'w', encoding='utf-8') as f:
    json.dump(de, f, ensure_ascii=False)
print(f"Part 3: {len(de)} articles total")
